### ISSUE TITLE
webdriver-manager update does not use new chromedriver 2.24

### ISSUE THREAD

**Issue by maccurt** [angular/webdriver-manager#102]
There is a new version of chromedriver 2.24 when you do a webdriver-manager update it does not pull it in. The current version of Chrome does not work with 2.22 when you send tab keys

**Comment by maccurt** [comment]
I am using npm install  -g webdriver-manager. When I look on git hub, it does look like the config.json file does have 2.24  in it. So I am not sure what the issue is. Please advice. https://github.com/angular/webdriver-manager/commit/5241fc14eaf2b5cdf4b35362f260f6973cea0b1e

**Comment by maccurt** [comment]
After downloading webdriver-manager-10.2.3, I see it is still using chromedriver 2.22 which does not work with the latest version of crhome.  I assume there needs to be a release..

**Comment by maccurt** [comment]
I was able to temporarily solve this by running this command webdriver-manager update --versions.chrome 2.24

**Comment by paradox41** [comment]
Related to #93 I think

**Comment by naterkane** [comment]
i have no idea how that worked for you @maccurt as since chromedriver 2.23 the binary has been 64 bit and not 32 bit... so the url it tries to pull the .zip from doesn't exist.

```shell
node_modules/protractor/bin/webdriver-manager update --versions.chrome 2.24

[22:33:24] I/downloader - chromedriver: downloading version 2.24
[22:33:24] I/downloader - curl -o /Users/naterkane/Projects/tenon/iscomplextable/node_modules/webdriver-manager/selenium/chromedriver_2.24mac32.zip https://ch
romedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
[22:33:24] I/update - selenium standalone: file exists /Users/naterkane/Projects/tenon/iscomplextable/node_modules/webdriver-manager/selenium/selenium-server-
standalone-2.53.1.jar
[22:33:24] I/update - selenium standalone: v2.53.1 up to date
[22:33:24] E/downloader - Error: Got code 404 from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
[22:33:24] E/downloader - Error: Got error Error: ENOENT: no such file or directory, stat '/Users/naterkane/Projects/tenon/iscomplextable/node_modules/webdriv
er-manager/selenium/chromedriver_2.24mac32.zip' from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
```

**Comment by maccurt** [comment]
Naterkane let me verify it actually worked.  I did it on a different machine than where my codebase is, on that machine I copied the 2.24 exe there  and renamed it to 2.22. Let me re-check.

**Comment by jkndrkn** [comment]
I, also, am unable to install 2.24:

```
node_modules/webdriver-manager/bin/webdriver-manager update --versions.chrome=2.24
webdriver-manager: using local installed version 10.2.3
[11:04:46] I/downloader - chromedriver: downloading version 2.24
[11:04:46] I/downloader - curl -o /Users/jderiksen/exactech/vagrant/prog/dgf-frontend/node_modules/webdriver-manager/selenium/chromedriver_2.24mac32.zip https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
[11:04:46] E/downloader - Error: Got code 404 from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
[11:04:46] I/update - selenium standalone: file exists /Users/jderiksen/exactech/vagrant/prog/dgf-frontend/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar
[11:04:46] I/update - selenium standalone: v2.53.1 up to date
[11:04:46] E/downloader - Error: Got error Error: ENOENT: no such file or directory, stat '/Users/jderiksen/exactech/vagrant/prog/dgf-frontend/node_modules/webdriver-manager/selenium/chromedriver_2.24mac32.zip' from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
```

No file named chromedriver_mac32.zip exists here: http://chromedriver.storage.googleapis.com/index.html?path=2.24/

**Comment by robbsherwin** [comment]
Does anyone know where documentation is for making webdriver-manager use the 64 bit version of the Mac chromedriver instead of defaulting to the 32 bit version (which isn't there, as others have noted, for 2.24).

**Comment by jfrej** [comment]
I think all of this has already been fixed but not released yet. The latest tagged and released version is 10.2.3, from August 24.

The webdriver version was changed to 2.24 in September, here: https://github.com/angular/webdriver-manager/pull/92

And the 64bit change is from October, here: https://github.com/angular/webdriver-manager/commit/946ee005f7d316fd2d404c4bdbeae9a3802051af

But none of this has been published to npm, so you might have to wait or point your package.json at github. Or clone the repo.

On Linux/Windows, if you just run `node_modules/protractor/bin/webdriver-manager update --versions.chrome 2.24`, you need to manually amend config.json to use version 2.24. Otherwise it will keep looking for 2.22.

**Comment by naterkane** [comment]
@jkndrkn @maccurt  it has to do with where the filename is constructed before the download is initiated... though stupid, it looks like there needs to be a switch where v2.23 and above are given the `64` string, and v2.22 and below are given the `32` string.

there are two places in the code where this filename is constructed for some reason, and I presume it would need to be handled in both places. 

i don't have any time to submit a PR this week, however if nobody has any availability, I can get it sorted and submit a PR over the weekend probably.

**Comment by paradox41** [comment]
As stated earlier in this thread, this has already been fixed. It just
hasn't been released yet.

**Comment by mgiambalvo** [comment]
Sorry about that! We'll do a new release today.

**Comment by naterkane** [comment]
Wooohoooo

- sent from my potato

**Comment by maccurt** [comment]
I appreciate it getting fixed. I use it on my personal project and the company I work for uses Telerik Test Studio to test an Angular App, and I really want to use it to show them how I did it with protractor with less fuss, I appreciate it.

**Comment by plynchnlm** [comment]
I think anytime a new chromedriver is needed for the current Chrome, a new release of webdriver-manager needs to be tagged ASAP.  I see the update to config.json was made September 12th, which is just over a month ago.  I don't know how people have been managing to run their tests if they use Chrome.

**Comment by iain** [comment]
It broke today, because Chrome released v54 today, which is the first version that doesn't work with chromedriver 0.22.

However, what is on NPM and in the git releases right now is not working.

This commit needs to be part of the relase for it to work: https://github.com/angular/webdriver-manager/commit/946ee005f7d316fd2d404c4bdbeae9a3802051af

**Comment by plynchnlm** [comment]
It broke for me yesterday. (https://googlechromereleases.blogspot.com/ says 54 was released yesterday, which coincidentally was the first time I had tried to run my tests in a while.)  One day's delay is not so bad.

**Comment by maccurt** [comment]
I had problems with chrome 2-3 weeks ago if I tried to send a tab key ,2.24 does fix that. Either way, I am happy someone is fixing it. As a developer I understand things happen.. Oh do they happen..

**Comment by iain** [comment]
while we're waiting for a new release, here is something you can do as a workaround:

* Change `"chromedriver": "2.22",` to `"chromedriver": "2.24",` in `node_modules/webdriver-manager/built/config.json`
* Change `mac32` to `mac64` in `node_modules/webdriver-manager/built/lib/binaries/chrome_driver.js`

**Comment by jkndrkn** [comment]
Thanks @iain, that workaround worked great for me.

**Comment by gitshanmu** [comment]
Thanks iain!The Workaround helped.I can run my tests now.

**Comment by cnishina** [comment]
Release 10.2.4 is out with the fix for chromedriver 2.24. The chromedriver fix was with pull request https://github.com/angular/webdriver-manager/pull/92.

**Comment by shavo007** [comment]
for 2,24 i get404:

Error: Got code 404 from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip

**Comment by cnishina** [comment]
@shavo007 Please use the latest release: 10.2.8.

**Comment by shavo007** [comment]
Thanks for the reply. I'm using the latest version of protractor node module. It this version reflected there?

**Comment by cnishina** [comment]
Look at Protractor's package.json in `node_modules/protractor/`.  It should say that the webdriver-manager version is "^10.2.8".

**Comment by shavo007** [comment]
Will do later today when I get into the office. Thanks.

**Comment by shavo007** [comment]
@cnishina  the version of protractor is "version": "3.3.0". I see the dependency for webdriver is   "selenium-webdriver": "2.52.0". That correct?

**Comment by shavo007** [comment]
@cnishina  all good. version of protractor was rather old. i bumped it to ^4.0.11. It then downloaded chrome driver for mac webdriver-manager/selenium/chromedriver_2.25mac64.zip.

Works like a charm now.
