### ISSUE TITLE
Boolean command line options are broken

### ISSUE THREAD

**Issue by thorn0** [angular/webdriver-manager#110]
The help says there is the `--gecko` option, `true` by default, but I can't find how to set it to `false`. I tried "--gecko=false", "--gecko false", "--no-gecko", "--gecko=0". Nothing works.

The other boolean command line options are broken as well. It's impossible to pass false to them.

**Comment by thorn0** [comment]
The other boolean command line options are broken as well. It's impossible to pass false to them.

**Comment by axelssonHakan** [comment]
Having the same issue with webdriver-manager update --standalone false
Causing unnecessary downloads

**Comment by sjelin** [comment]
Should be fixed soon - sorry about this!
