### ISSUE TITLE
Update fails to download geckodriver v0.10.x+ on Mac OS X

### ISSUE THREAD

**Issue by kohanyirobert** [angular/webdriver-manager#111]
```
./node_modules/.bin/webdriver-manager update --versions.gecko=0.11.1
...
[14:13:48] E/downloader - Error: Got code 404 from https://github.com/mozilla/geckodriver/releases/download/0.11.1/geckodriver-0.11.1-mac.tar.gz
...
```

This happens because since v0.10.x the [geckodriver releases](https://github.com/mozilla/geckodriver/releases) are named differently.

[The suffix `-mac.tar.gz` is hardcoded](https://github.com/angular/webdriver-manager/blob/master/lib/binaries/gecko_driver.ts#L18). It's `-macos.tar.gz` from now on. Either the code should be changed or the geckodriver release name should be reverted to the old name (not sure why they needed to change it).

**Comment by sjelin** [comment]
Issue confirmed.  @cnishina, you designed the download strategy (I think?), so I'll assign this to you.

**Comment by cnishina** [comment]
Adding @mgiambalvo to this ticket.
