### ISSUE TITLE
webdriver-manager update always downloads, even if version is already downloaded

### ISSUE THREAD

**Issue by asgoth** [angular/webdriver-manager#117]
`webdriver-manager update` always downloads, even if version is already downloaded. 

I had a quick look to what could cause the problem, and it seems the FileManager.toDownload function always resolves `true`:

https://github.com/angular/webdriver-manager/blob/master/lib/files/file_manager.ts#L169

**Comment by sjelin** [comment]
Closing in favor of https://github.com/angular/webdriver-manager/issues/127
