### ISSUE TITLE
webdriver-manager spec files also run when Protractor tests are run. screenshots included.

### ISSUE THREAD

**Issue by chowdhurian** [angular/webdriver-manager#126]
## Description

When running own tests, webdriver-manager spec files are also running.

## Tests from the following spec files are running:
webdriver-manager/spec/files/fileManager_spec.ts
webdriver-manager/spec/files/downloader_spec.ts
webdriver-manager/spec/webdriver_spec.ts

### Externally linked or see embedded below:
[screenshot 1](https://i.stack.imgur.com/i35mW.png)
[screenshot 2](https://i.stack.imgur.com/MlpMe.png)

![screen shot 2016-11-01 at 12 01 54 2](https://cloud.githubusercontent.com/assets/10335475/19904100/8a36fe02-a02e-11e6-9653-98f56fe0c107.png)
![screen shot 2016-11-01 at 12 02 00 2](https://cloud.githubusercontent.com/assets/10335475/19904104/8ec6dff0-a02e-11e6-96af-9543766732c0.png)

**Comment by sjelin** [comment]
How are you installing `webdriver-manager`?  The tests aren't published to npm

**Comment by chowdhurian** [comment]
I'm using `webdriver-manager` that's included when installing Protractor globally with npm. 🙂

The command `webdriver-manager update` works. 🛠

**Comment by chowdhurian** [comment]
This could be relevant.

Last week webdriver-manager wasn't working. I updated Protractor, then used `webdriver-manager update` successfully. 🛠

Then it was working again!

This new issue showed up soon(?) after.

**Comment by sjelin** [comment]
That is extremely strange.  What command are you using to execute your tests?

**Comment by chowdhurian** [comment]
`CI=true LM=true protractor protractor.conf.js --suite someSuite`

1. `CI=true` and `LM=true` are env variables for my conf.js
2. It only runs webdriver-manager specs when I **don't** use the `--suite` flag and specify a spec file. So, only with `CI=true LM=true protractor protractor.conf.js`

**Comment by cnishina** [comment]
Verified. We will fix this.  The TypeScript files are being transpiled to *.js and the `built/spec` directory is being published.

**Comment by cnishina** [comment]
Closed with https://github.com/angular/webdriver-manager/pull/134.
