### ISSUE TITLE
Add e2e test

### ISSUE THREAD

**Issue by cnishina** [angular/webdriver-manager#16]
It will be good to have some tests launching node bin/webdriver-manager:
- start with no selenium folder
- clean with no selenium folder
- status with no selenium folder
- start with a selenium folder but no selenium jar file
- update - check files are downloaded
- status - check files are there
- clean - remove downloaded files

**Comment by macroking** [comment]
webdriver-manager clean command leaves 

- chrome-response.xml
- gecko-response.json
- standalone-response.xml

Is it expected?

**Comment by cnishina** [comment]
It probably should remove it.

**Comment by cnishina** [comment]
So the files for xml and json make sense. These are used as cached responses. e2e tests have been added to version 13. This issue is done!
