### ISSUE TITLE
Document update-config.json and how this is used in Protractor

### ISSUE THREAD

**Issue by cnishina** [angular/webdriver-manager#169]
closes #169

**Comment by benjaminapetersen** [comment]
Possible to provide an example of what this file is supposed to look like?  Trying to see if I can spoof it when:

```bash 
~~ 
```
If I happen to have a `selenium-standalone-server` jar, I should be able to manually create this file to hook things up if `webdriver-manager update` is unable to work successfully.

Related to issues #270 & #269.

**Comment by benjaminapetersen** [comment]
Prev comment, this might assist: https://medium.com/@cnishina/webdriver-manager-a-node-module-c33a820f5eb
