### ISSUE TITLE
Unexpected token ... (tripal dot) is coming when i am trying to execute protracter with eclipse

### ISSUE THREAD

**Issue by Vikrantojha** [angular/webdriver-manager#192]
@cnishina 
Hi All,
I am setting up protractor with eclipse. and when trying to execute script i am getting below error.
I have webdriver-manager version : 11.1.1
Protractor version: Version 4.0.14
node version v6.9.2

can anyone help me on how to fix below error:

\node_modules\protractor\built\logger.js:75
    info(...msgs) {
         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\Selenium\Protractor\ProtrectorSetup\node_modules\protractor\built\configParser.js:5:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by cnishina** [comment]
This should work with node 6. Could you test this via the command line (not Eclipse)? This is an error that I've seen before for before node 6. Could Eclipse be using a different version of node?

**Comment by Vikrantojha** [comment]
Thanks for your reply @cnishina 
from command line its working fine. but from eclipse i am still facing same issue. i have only node version v6.9.2 installed in my system and i think eclipse also do use same node.
Please help me to resolve this issue.

**Comment by Vikrantojha** [comment]
Thanks @cnishina 
your last statement has worked for me. actually eclipse was using a different version of node. eclipse was using node version v4.2.4 and i believe this was the issue as i update the version to 6.9.2 and its worked.

just mentioning steps to resolve this issue below for the learning like to in case anyone will face same issues:

1. To check the node.js version in your eclipse, go to > window > Preferences 

2.  under angulerJS>Protractor , there is option in right side "Node.js install", select Native node js in drop-down menu. and try..

3. if still it doesn't work, you can select other default option from drop-down menu 

4. navigate to the folder location in your system which is being pointed by eclipse to use node.js, 
once you reach to the location, update your node. js file. 

5.  update from command line by using update command or you can replace node.js file from your native location (in my case, i have copied from C:\program file\nodejs). i coped node.js file and past it to the location where eclipse was pointing.


Thanks

**Comment by cnishina** [comment]
Great. Closing this issue.

**Comment by ManojSudhagar** [comment]
@Vikrantojha: Thanks a lot, buddy . Finally it worked after following your solution.

**Comment by ganesh20215** [comment]
Thanks you Vikrant. Solution is working fine
