### ISSUE TITLE
UnreachableBrowserException

### ISSUE THREAD

**Issue by montgoew** [angular/webdriver-manager#194]
Windows 7
Chrome 55
ChromeDriver 2.27
Selenium Server 2.53.1
Node 6.0.0
Visual Studio 2013

For about 4 weeks, I've been trying to run WebDriver scripts against Chrome and failing. I first started in protractor. webdriver-manager starts up just fine, as far as I can tell (01_start_webdriverManager.txt), and sits on port 4444 waiting. I execute my script from protractor (02_conf.js), and it blows up (03_webdriverManager_triedToConnect.txt and 04_protractorSideOfError.txt).

Even if I just go to the localhost and start a session, the same results come out of log file #03.

So I went over to Visual Studio. I created a fresh unit test application, fetched the Nuget packages for WebDriver and Chromium, and the test failed, timed out.

Since then, I've checked my environment variables, upgraded to Java 1.8, and reinstalled Chrome a few times. I cleaned out protractor and webdriver and reinstalled those. I tried different versions of ChromeDriver (2.25, 2.26, 2.27) and Selenium Server (2.53.1, 3.0.1, which won't start at all). I've tried various settings in protractor - all to no avail; however, Visual Studio is back up and running, which is interesting.
[01_start_webdriverManager.txt](https://github.com/angular/webdriver-manager/files/712791/01_start_webdriverManager.txt)
[03_webdriverManager_triedToConnect.txt](https://github.com/angular/webdriver-manager/files/712792/03_webdriverManager_triedToConnect.txt)
[04_protractorSideOfError.txt](https://github.com/angular/webdriver-manager/files/712793/04_protractorSideOfError.txt)
[05_selenium3_0_1.txt](https://github.com/angular/webdriver-manager/files/712794/05_selenium3_0_1.txt)

[02_conf.js.txt](https://github.com/angular/webdriver-manager/files/712795/02_conf.js.txt)

I started ChromeDriver directly (chromedriver_2.27 --verbose --log-path=chromedriver.log), and then ran the protractor test against that port, and it worked! So, that's something.

I'm on a corporate machine, and all of my buddies are all able to get it working, and I'm able to get it working on a couple of independent machines. I'm pretty sure that the problem isn't me, but not 100% sure. ;)

Thanks for the help. I've tried everything I can think of.

**Comment by cnishina** [comment]
This should be opened against Protractor. This issue does not appear to have an issue with downloading the binary. When opening a bug with Protractor, please also add the Protractor version you are using.
