### ISSUE TITLE
Cannot run Webdriver-manager - error "using global installed version 11.1.1"

### ISSUE THREAD

**Issue by phillipclarke29** [angular/webdriver-manager#195]
I get webdriver-manager: using global installed version 11.1.1  !9260
zsh: command not found: webdriver-manager:
/usr/local/lib/node_modules/webdriver-manager/built/lib/cli/logger.js:66
    info(...msgs) {
         ^^^

**Comment by cnishina** [comment]
What version of node are you using? Please read the changelog. You should be on node 6+. Closing this issue since the spread operator has been previously discussed.
