### ISSUE TITLE
 ECONNREFUSED connect ECONNREFUSED 127.0.0.1:43744

### ISSUE THREAD

**Issue by caneraydinbey** [angular/webdriver-manager#196]
> vegan@vegan:$ nodejs -v
> v5.12.0
> vegan@vegan:$ npm -v
> 3.8.6
> 
> but still not working.
> 
> chromedriver is up to date.
> gateway@0.0.0 /home/vegan/xx-xx/gateway
> └─┬ protractor@3.1.1
> └─┬ selenium-webdriver@2.48.2
> ├── tmp@0.0.24
> ├── ws@0.8.1
> └─┬ xml2js@0.4.4
> └── sax@0.6.1,
> 

the error is

```

> `Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:43744
>     at ClientRequest.<anonymous> (/home/vegan/xx-xx/gateway/node_modules/selenium-webdriver/http/index.js:174:16)
>     at emitOne (events.js:90:13)
>     at ClientRequest.emit (events.js:182:7)
>     at Socket.socketErrorListener (_http_client.js:306:9)
>     at emitOne (events.js:90:13)
>     at Socket.emit (events.js:182:7)
>     at emitErrorNT (net.js:1265:8)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> From: Task: WebDriver.createSession()
> `

```

Then i removed

 /xx/vegan/hb-xx/gateway/node_modules/protractor

whicvh has selenium webddriver. Then npm install gulp install and it downloaded again:

`└─┬ protractor@3.1.1 
  ├── adm-zip@0.4.7 
  ├── glob@6.0.4 
  ├─┬ jasmine@2.4.1 
  │ └─┬ glob@3.2.11 
  │   └─┬ minimatch@0.3.0 
  │     └── lru-cache@2.7.3 
  ├── jasminewd2@0.0.8 
  ├─┬ request@2.67.0 
  │ ├─┬ bl@1.0.3 
  │ │ └── readable-stream@2.0.6 
  │ ├─┬ form-data@1.0.1 
  │ │ └─┬ async@2.1.4 
  │ │   └── lodash@4.17.4 
  │ ├── qs@5.2.1 
  │ └── tough-cookie@2.2.2 
  └─┬ source-map-support@0.4.10 
    └── source-map@0.5.6 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17`

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
