### ISSUE TITLE
webdriver-manager update --ignore_ssl no longer works on 12.0.1

### ISSUE THREAD

**Issue by kalypzo** [angular/webdriver-manager#207]
**Actual Behavior**
Run the following against webdriver-manager version 12.0.1:

> webdriver-manager update --ignore_ssl

It returns

    events.js:160
        throw er; // Unhandled 'error' event
        ^

    Error: self signed certificate in certificate chain
        at Error (native)
        at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
        at emitNone (events.js:86:13)
        at TLSSocket.emit (events.js:185:7)
        at TLSSocket._finishInit (_tls_wrap.js:584:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)

**Expected Behavior**
Based on version 10.2.5, I'm expecting something similar to:

    webdriver-manager: using local installed version 10.2.5
    [13:51:46] I/downloader - ignoring SSL certificate
    [13:51:46] I/downloader - ignoring SSL certificate
    [13:51:46] I/downloader - ignoring SSL certificate

**Why is this required?**
I'm working on an application for my company which is using some security measure that replaces a site's certificate with its own self-signed certificate. As a result, I have two options. Add my certificate to a store and somehow get webdriver-manager to use it. This was my first option, but couldn't find a way, maybe I'm missing something. Easier alternative, just ignore SSL, unsafe, but avoids all the headache.

**Do you have any alternatives?**
Can you pick up the certificates I supply to ca or cafile in my .npmrc file? That would be very helpful; otherwise, I end up having to subvert security just to install things.

**Comment by royling** [comment]
The fix released in 12.0.3 did not resolve the problem, this has to be reopened.

**Comment by cnishina** [comment]
Please try again. 12.0.4 should have your fix.

**Comment by kalypzo** [comment]
Thanks! Will take a look.

**Comment by perfectr** [comment]
I have this same situation of a corporate proxy intercepting SSL and inserting SSL certificate and I'm still getting the same error on release 12.0.4.

`$ npm ls webdriver-manager
cli-test@0.0.0 /Users/XXXXXX/Projects/CliTest
└─┬ protractor@5.1.1
  └── webdriver-manager@12.0.4 

$ webdriver-manager update --proxy http://xx.xx.xx.xx:111111 --ignore_ssl
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
`

**Comment by hasmukh** [comment]
I am also getting the same error while trying `npm install`. Is there any attempted solution or workaround for this issue ?

**Comment by royling** [comment]
@perfectr https://github.com/request/request/issues/2061, related. you may try the workaround provided there and let us know if it works.

**Comment by dineiar** [comment]
I confirm that in webdriver-manager 12.0.6 the `--ignore_ssl` argument is working.

It generates `I/http_utils - ignoring SSL certificate` messages and update correctly.
