### ISSUE TITLE
provide a way to make GitHub requests authenticated to prevent error: gecko driver not downloading / failing with promise error

### ISSUE THREAD

**Issue by cnishina** [angular/webdriver-manager#216]

**Comment by MJDSys** [comment]
I see this issue all the time on Travis CI.  You can see an example build log here: https://travis-ci.org/CCJ16/registration/jobs/207167621#L2040 .

I think the issue might be that Github's API's rate limit is being hit.  I submitted a PR (#217) to detect that case, to hopefully get more information about what is going on.

**Comment by cnishina** [comment]
I think the rate limit error message is helpful. I haven't seen this happen recently so I plan to close it.

**Comment by rdbaron** [comment]
@cnishina We have recently started seeing this error a few times per day.  Here is the output we get:

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to make Github request, rate limit reached.`

^^ This is when trying to download https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-win64.zip

We are on webdriver-manager 12.0.3

**Comment by cnishina** [comment]
This is an unauthenticated rate limit set by GitHub (See https://developer.github.com/v3/search/#rate-limit). 

What we are doing is downloading the GitHub release json for gecko driver and saving the file to the `selenium/` folder.  The release json is great because it  allows us to find the latest and greatest binary every time without maintaining a list of binary versions. Also, because we have a saved file, we only refresh the file if the file is older than an hour.

However, I could see this becoming a problem in CI if you are downloading everything on each build. If you are in CI and downloading a new set of node_modules, think about using the `--out_dir` option. You could set an absolute path outside of your project where the binaries will be maintained. What will happen is that multiple projects could then be launched and refer to the same GitHub release json file and not download a new one. This should keep you under the GitHub unauthenticated rate limit.

So, when doing an `update`, this will look like:
```
webdriver-manager update --out_dir /some/path/to/selenium
```

And starting the server would look like:
```
webdriver-manager start --out_dir /some/path/to/selenium
```

**Comment by rdbaron** [comment]
Thanks for the reply.  Everything you've said makes sense, however we use a cloud based CI tool (CircleCI) so sharing between executions is not really an option.  In our particular case, we can just set `--gecko false` because nothing we do is using that driver. 

I only mention it because I could see this being an issue for others.

**Comment by cnishina** [comment]
Good point. I can see that being a big problem since circle CI has probably makes requests from the same set of IP addresses. We'll have to look into giving the user a way to set authenticated GitHub requests.

**Comment by joymon** [comment]
I am facing the same GitHub API limits when I am using protractor from AppVeyor hosted CI. Any updates or workarounds to solve the GitHub download

**Comment by DmitryRomaniuk** [comment]
@cnishina I think problem with letter v, when I write webdriver-manager update --versions.gecko=v0.18.0, then all works correctly

**Comment by cnishina** [comment]
Done! Please look at version 13. It has support for GitHub authentication.
