### ISSUE TITLE
'webdriver-manager start' should not update anything

### ISSUE THREAD

**Issue by attila123** [angular/webdriver-manager#220]
I #211  @cnishina wrote: "During the 'start' method it validates the cache, and downloads a new list if it is stale. It does not download new binaries. If you do not have the latest, 'start' does not work. This forces the user to make a decision: should I pin a version or run update again to get the latest version."

As a developer / build engineer
- I want 'webdriver-manager start' to do exactly what it says: start selenium and chrome driver, etc. and do not try to do the above described downloading. I consider this an an undesirable side-effect.
- I want a predictable build environment, and I want to update selenium, chrome etc. drivers in a controlled way: that is, only via 'webdriver-manager update'. Otherwise my tests may break and it may even trigger forced browser updates as well.
- I don't want to complicate the 'webdriver-manager start' command with any versions parameters just to pin the versions, e.g. 'webdriver-manager start --versions.standalone 3.2.0 --versions.chrome=2.27' neither I want to hear my colleagues whining about it :), or gruble why I updated webdriver-manager from '11.1.1' in the first place. :)
- I am not interested in the internals of webdriver-manager, e.g. how its cache works.
- If you need a separate functionality like this, you should do it with a separate webdriver-manager command. I still wonder what is the benefit though, because I can test the new versions or roll back to old ones simply with 'webdriver-manager update' (perhaps together with 'webdriver-manager clean').
- I want any attempt to connect to the Internet (e.g. for any updates) clearly logged by default.

**Comment by cnishina** [comment]
When I stated you could put in a "pull request", I meant actually writing code and fixing it. This issue appears to be the same thing restated from the last issue. I'll leave this open so you can put in a pull request.

**Comment by attila123** [comment]
Ah I see, I thought PR was something like 'problem report'.
I will consider it, but I don't promise anything.

**Comment by cnishina** [comment]
I think you do bring up a good point. If a user is developing their Protractor tests / Angular application offline, then the extra call to the internet could be problematic. We could just not validate the cache and use the latest item no matter how old it is. When a user calls `update` is when we will validate the cache and potentially download new binaries.

A quick nit on your issue. You should think about wording your issues better. Your last two issues have across as a complaints. It is very difficult to find a solution when reading a complaint. However, after reading your issue multiple times, I was able to find a scenario where this could be helpful for the entire community. 

Possibly this could have been worded as "I'm developing a web application on localhost and I need offline capabilities when starting a selenium standalone server. Currently running webdriver-manager start throws an error when I do not have internet access." I would have been able to relate this to a reasonable enhancement.

Anyway I currently do not have the bandwidth currently to take this on. Maybe I might have time this month or the next month.

**Comment by attila123** [comment]
I agree that #211 is a mess, because I did not know what is going on (no log was written about the updating at 'start') and did not read the changelog, because I did not know that it was the de-facto documentation.
In this issue I tried to clearly explain how changes done in 12.0.0 to 'webdriver-manager start' violate the separation of concerns, and add a counter-intuitive side-effect to 'start' which oppose/hinder all the use cases I can think of.
First of all there would be need for a clear understanding of what motivated these changes in 12.0.0 (see quoted below) and what are the benefits for which use cases. Then a solution could be designed which would support all the use cases. Quoting from the changelog:

"12.0.0
Changes to update

This release gets the latest release for selenium standalone, chromedriver, iedriver, and gecko driver by downloading and parsing either a json or xml file. These json or xml files are cached in the selenium directory. This means for users that provide an alternative cdn will also be required to provide the proper xml or json server response to find these binaries.

Since we are always downloading the latest, the config.json versions will no longer be a place to override these.
Changes to start

If a new release is out and you have old binaries, running webdriver-manager start without specifying any versions should throw an error. The error will tell the user that the binary is not present."

**Comment by cnishina** [comment]
Closing with #232.

**Comment by keerthindurthi** [comment]
I was unable to get working with 
"webdriver-manager update --versions.chrome=2.26" and

 webdriver-manager start -versions.chrome=2.26 --detach & ng e2e --protractor-config=protractor-ci.conf.js || exit 1
build	28-Jun-2018 09:33:11	[INFO] 
build	28-Jun-2018 09:33:12	[INFO] [09:33:12] I/start - java -Djava.security.egd=file:///dev/./urandom -Dwebdriver.chrome.driver=/var/atlassian/bamboo-agent/xml-data/build-dir/AIRVIEW-SUI38-JOB1/settingsui/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.40 -Dwebdriver.gecko.driver=/var/atlassian/bamboo-agent/xml-data/build-dir/AIRVIEW-SUI38-JOB1/settingsui/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.21.0 -jar /var/atlassian/bamboo-agent/xml-data/build-dir/AIRVIEW-SUI38-JOB1/settingsui/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.13.0.jar -port 4444

It gets the latest version  from internet instead of the version i mentioned getting below error 
build	28-Jun-2018 09:33:40	[INFO]       - Failed: [JavaScript Error: "b is null" {file: "file:///tmp/anonymous153187679386654570webdriver-profile/extensions/fxdriver@googlecode.com/components/synthetic-mouse.js"

**Comment by keerthindurthi** [comment]
Is the issue fixed as mentioned i kept the version.chrome 2.26 to use but its not picking that version but it getting latest from internet, how can resolve this issue.

 webdriver-manager start -versions.chrome=2.26 --detach & ng e2e --protractor-config=protractor-ci.conf.js || exit 1
build	28-Jun-2018 09:33:11	[INFO] 
build	28-Jun-2018 09:33:12	[INFO] [09:33:12] I/start - java -Djava.security.egd=file:///dev/./urandom -Dwebdriver.chrome.driver=/var/atlassian/bamboo-agent/xml-data/build-dir/AIRVIEW-SUI38-JOB1/settingsui/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.40 -Dwebdriver.gecko.driver=/var/atlassian/bamboo-agent/xml-data/build-dir/AIRVIEW-SUI38-JOB1/settingsui/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.21.0 -jar /var/atlassian/bamboo-agent/xml-data/build-dir/AIRVIEW-SUI38-JOB1/settingsui/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.13.0.jar -port 4444

Below is the error i'm seeing runing selenium tests with Firefox 45.
build	28-Jun-2018 09:33:40	[INFO]       - Failed: [JavaScript Error: "b is null" {file: "file:///tmp/anonymous153187679386654570webdriver-profile/extensions/fxdriver@googlecode.com/components/synthetic-mouse.js"

**Comment by keerthindurthi** [comment]
sdfsdfs

**Comment by keerthindurthi** [comment]
Hi @attila123 @cnishina , is the issue resolved, i got the latest protractor/ web driver manager i'm still getting drivers from internet, Any suggestions or workarounds how you resolved this issue. 

 webdriver-manager start -versions.chrome=2.26 --detach & ng e2e --protractor-config=protractor-ci.conf.js || exit 1
build	28-Jun-2018 09:33:11	[INFO] 
build	28-Jun-2018 09:33:12	[INFO] [09:33:12] I/start - java -Djava.security.egd=file:///dev/./urandom -Dwebdriver.chrome.driver=/var/atlassian/bamboo-agent/xml-data/build-dir/AIRVIEW-SUI38-JOB1/settingsui/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.40 -Dwebdriver.gecko.driver=/var/atlassian/bamboo-agent/xml-data/build-dir/AIRVIEW-SUI38-JOB1/settingsui/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.21.0 -jar /var/atlassian/bamboo-agent/xml-data/build-dir/AIRVIEW-SUI38-JOB1/settingsui/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.13.0.jar -port 4444

Below is the error i'm getting runing protractor tests in firefox 45 using web driver manager

build	22-Jun-2018 15:47:45	[INFO]       - Failed: [JavaScript Error: "b is null" {file: "file:///tmp/anonymous3374909239406097458webdriver-profile/extensions/fxdriver@googlecode.com/components/synthetic-mouse.js" line: 10294}]'[JavaScript Error: "b is null" {file: "file:///tmp/anonymous3374909239406097458webdriver-profile/extensions/fxdriver@googlecode.com/components/synthetic-mouse.js" line: 10294}]' when calling method: [wdIMouse::move]

**Comment by cnishina** [comment]
This might still be happening. Opening this up again but I'm working on a separate solution.

**Comment by gitmalong** [comment]
I can confirm that issue with webdriver-manager 12.1.0.

**Comment by jpreese** [comment]
FWIW I ran into this at work not too long ago and it is/was incredibly confusing.

https://reesespieces.io/the-importance-of-naming/

**Comment by cnishina** [comment]
FWIW I removed it but people still have had issues. Thanks for your input?

**Comment by cnishina** [comment]
I already removed that portion of code but do not understand why users still have this issue. But thanks for your blog post?

**Comment by jpreese** [comment]
It works great for us! 

I think the only issue is that start does more than just start under the hood. It's not necessarily a bad thing, just a little confusing. It's a design decision and it has been documented as such. Just need to make users more aware of the behavior.

**Comment by cnishina** [comment]
Okay there are no longer any side effects. This is as of version 13.0.0. In version 13.0.0 start only runs the java command. Closing this issue! If this is still an issue on version 13, let me know.
