### ISSUE TITLE
Available driver version XML is cached for longer than one hour

### ISSUE THREAD

**Issue by nickcmaynard** [angular/webdriver-manager#221]
As stated in the CHANGELOG (https://github.com/angular/webdriver-manager/blob/master/CHANGELOG.md#features) the index XML file is cached for 1 hour.

However, this doesn't appear to be the case.  My selenium index was last downloaded at 10am this morning (it's now 8 hours later), and no new version is being pulled down.  I know there's a new version, as I've checked it.

I'm suspicious this is to do with these magic numbers:
https://github.com/angular/webdriver-manager/blob/5c1de8e8c65297804de12ecae2c8dc74a9f0c386/lib/binaries/config_source.ts#L56
https://github.com/angular/webdriver-manager/blob/5c1de8e8c65297804de12ecae2c8dc74a9f0c386/lib/binaries/config_source.ts#L175

... which represent the number of seconds for *10* hours, not 1 hour.  An extra zero.

Detected as part of examining angular/protractor/issues/4141.

**Comment by cnishina** [comment]
Wow, one extra zero. Now if I could only manage that in a paycheck. This is definitely a bug and I should have a fix out.
