### ISSUE TITLE
Webdriver-Manager Start Certificate Error

### ISSUE THREAD

**Issue by paulco16** [angular/webdriver-manager#229]
I am getting the following error below when trying to start webdriver-manager.

It is working yesterday, after restarting it today, I am now getting a certificate error.

I enter --ignore_ssl, added proxy/https-proxy on User Variables and I already tried running the cmd as an administrator.

Error:
```  C:\Users\<user>\AppData\Roaming\npm>webdriver-manager start --ignore_ssl 
  events.js:160
        throw er; // Unhandled 'error' event
        ^

  Error: unable to get local issuer certificate at Error (native)
      at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
      at emitNone (events.js:86:13)
      at TLSSocket.emit (events.js:185:7)
      at TLSSocket._finishInit (_tls_wrap.js:610:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)```

When updating, I was able to update successfully without an error.

I was advised to log a bug here on github thru [stackoverflow](http://stackoverflow.com/questions/42995459/webdriver-manager-start-certificate-error)

**Comment by royling** [comment]
`ignore_ssl / proxy` options are not supported in `webdriver-manager start` now.
In order to fix this, need to do the same as what is done in `update` command. Right?

**Comment by cnishina** [comment]
`start` should not make a web call, use the cache, and launch the server.

**Comment by cnishina** [comment]
Closing with #232. The web requests do not happen on `start`.

**Comment by cnishina** [comment]
Plan to do a release later today.

**Comment by parky128** [comment]
@cnishina - I am having problems with version 12.0.5 when issuing the `webdriver-manager start` command and am getting the `unable to get local issuer certificate` error as mentioned in this issue. I wasn't seeing this a few days ago and havent updated webdriver or any related components recently. I notice your latest comment mentions about planning to do a release, has this been done? I couldnt see any later versions to grab from npm if so. Thanks

**Comment by cnishina** [comment]
12.0.5 was released April 24th. This version should fix issue with the `start` command. What happens now is on `start`, no web requests happen to validate the cache. I forgot to tag the release.

https://github.com/angular/webdriver-manager/releases/tag/12.0.5
