### ISSUE TITLE
Lower node version requirements for newer browser support

### ISSUE THREAD

**Issue by AndrewFinlay** [angular/webdriver-manager#234]
Hi there, 

We've run into some issues regarding keeping our browser, test-runner and node versions in sync over the years while using Protractor and we're hoping for a few changes to make it easier.

Our test env is typically running at node 4 that is in LTS until early 2018, and we don't want to change our node version until necessary.  We run our e2e tests using Chrome and aim to keep it as up to date as possible.  

Currently it seems impossible to update the Chromedriver used by webdriver-manager past a level that is hard-coded in the repo.  This pushes users towards downloading the latest version of protractor or webdriver-manager when, it seems, all that is really needed is an updated chromedriver.  For us, the latest protractor/webdriver-manager also means that we need to move our test env to node 6, and either update our production code or run with different node versions for production and test.

Can we add a way to have webdriver-manager upgrade to be user configurable, and supporting of node versions that are currently in LTS?

Regards,
Andrew

**Comment by cnishina** [comment]
So why did Protractor update to node 6? Selenium-webdriver recently converted their control flow promises to native promises in ES6. Native promises are  supported in node 6.

Webdriver-manager also made a similar switch to node 6 to adopt the native promises. This was documented in the changelog. If you need a version that works with node 4, I would recommend  downgrading to a lower version of webriver-manager (^11.x.x).

**Comment by AndrewFinlay** [comment]
While this is kind of off topic, native promises were introduced in Node 4, so you'd expect them to be supported in Node 6.  Anyway your solution doesn't address the original problem, which is that the webdriver-manager update command only downloads the hard-coded 'latest' version of Chromedriver.  This means to use the latest version of Chrome, I need the latest version of webdriver unless I manually update it.
