### ISSUE TITLE
Update chromedriver version to 2.28

### ISSUE THREAD

**Issue by jonrigerths2** [angular/webdriver-manager#236]
The lastest Chrome (v57) appears to require ChromeDriver 2.28.

When running tests using 2.27, I receive the following errors:

`[16:45:26] W/launcher - Ignoring uncaught error WebDriverError: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.10.5 x86_64)`

If I override config.json locally to use 2.28 it fixes this error.

Are we able to get a webdriver-manager version that defaults to 2.28? Or is there a way for Protractor to specify this version?

**Comment by fyodorvi** [comment]
@jonrigerths2 how do you override it?

**Comment by armordog** [comment]
I got it to work by downloading the latest chromedriver manually and then replacing the existing "chromedriver_2.25.exe" in the webdriver-manager/selenium directory.

I had to give the new one the same name as the old one (chromedriver_2.25.exe)

**Comment by jonrigerths2** [comment]
@fyodorvi: I updated `webdriver-manager/built/config.json`, as @armordog pointed out. 

In my setup, webdriver-manager is actually inside the protractor package, so the full path ended up being: `node_modules/protractor/node_modules/webdriver-manager/built/config.json`

**Comment by cnishina** [comment]
Hopefully this provides some clarity:

So if you are downloading chromedriver 2.27 by default then you might be using an old version of webdriver-manager. The recent changes will always download the latest and greatest. I would recommend using the most recent version of Protractor to get the most recent version of webdriver-manager.

After you have the a recent version of webdriver-manager, you could pin the version that you would like to download and start.

```
webdriver-manager update --versions.chrome 2.28

webdriver-manager start --versions.chrome 2.28
```

Also, another quick note: webdriver-manager/built/config.json no longer is the way to override the version. I think I have an issue to remove the versions from the config.

**Comment by jonrigerths2** [comment]
Thanks @cnishina! I updated to the most recent version of Protractor and it's getting the latest ChromeDriver.
