### ISSUE TITLE
SIGINT causes unhandled error event

### ISSUE THREAD

**Issue by chrisgedrim** [angular/webdriver-manager#238]
# Steps to reproduce

1. Launch webdriver `$ ./bin/webdriver-manager start`
2. Wait for server to come up `... INFO - Selenium Server is up and running`
3. Send `SIGINT` (`⌃c`) to kill server

# Expected behaviour

Process shuts-down server cleanly

# Actual behaviour

Unhandled error is thrown

```
13:30:45.730 INFO - Selenium Server is up and running
^C[13:30:48] I/start - Staying alive until the Selenium Standalone process exits
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

This seems to be because Selenium have removed the ability to interact with the driver over http https://github.com/SeleniumHQ/selenium/issues/2958

**Comment by cnishina** [comment]
Shutting down does have an issue. This is duplicate for #199.

**Comment by chrisgedrim** [comment]
Sorry for the duplication, I did have a quick browse through the issues and couldn't see one that matched. I have a potential fix coded, just need to write the tests before I PR it

**Comment by cnishina** [comment]
Oh nice. I don't have bandwidth to hep here so PRs are totally welcomed! I think this also might help with the `--detach` command. I believe that is also using the shutdown web request.

**Comment by chrisgedrim** [comment]
Yea, I've tried to catch all of the instances of the shutdown command, it should be ready tomorrow

**Comment by cnishina** [comment]
That's awesome!

**Comment by chrisgedrim** [comment]
@cnishina I've had to add a new npm package, but that seems to be failing the build in circle...

**Comment by cnishina** [comment]
Let's leave this issue open. I'll take a look at it.

**Comment by angelblade27** [comment]
Has this been checked in?

**Comment by cnishina** [comment]
The --detach and shutdown work is done.

See https://github.com/angular/webdriver-manager/blob/master/lib/provider/selenium_server.ts#L122 and https://github.com/angular/webdriver-manager/blob/master/lib/provider/selenium_server.ts#L228

**Comment by cnishina** [comment]
Hmmm... this is the line I wanted.

https://github.com/angular/webdriver-manager/blob/master/lib/cmds/start.ts#L25 where we kill the server then kill the process.
