### ISSUE TITLE
(feature req) installation option for Chrome driver only

### ISSUE THREAD

**Issue by kgentes** [angular/webdriver-manager#240]
`webdriver-manager` comes default with both Chrome and Firefox.  In many cases (CEF testing, Chrome only testing), I have no need for Firefox binaries to be downloaded, and I would like to exclude them from being brought down with the initial install of drivers or with any later `webdriver-manager update` commands.

There is also the additional concern of having problems with Firefox driver just via the fact it is installed even thought I am not going to use it. An example of this is the recent [false-positive virus detection of geckodriver](https://github.com/mozilla/geckodriver/issues/671) by Windows Defender and Symatec , which recently broke our entire build process.

**Feature Request**: I would like to install and update webdriver-manager with an option for _Chrome only_.

**Comment by kgentes** [comment]
Incidentally, I originally thought that the `--chrome` switch might actually perform this function when used in the context of `webdriver-manager update --chrome`, however, this is appears to clearly **not** be the case, as it does the following:
```
webdriver-manager update --chrome

[16:58:11] I/file_manager - creating folder C:\git\myproj\node_modules\protractor\node_modules\webdriver-manager\selenium
[16:58:24] I/update - chromedriver: unzipping chromedriver_2.29.zip
[16:58:49] I/update - geckodriver: unzipping geckodriver-v0.16.0.zip
```
Since there is no documentation detailed on what the switch should actually do (only the `--help`, which doesn't indicate it is an exclusive switch), I am guessing it is not intended to be chrome **only**.

**Comment by cnishina** [comment]
But you can. This is a feature that exists.

`webdriver-manager update --standalone false --gecko false`

If you need to get a help menu, there is one:

`webdriver-manager help` or if you are in update and want to know the specific update help menu, `webdriver-manager update help`

**Comment by kgentes** [comment]
just to be sure I understand this, why is the ` --standalone false` part of this reply included here? I thought that was only dealing with whether or not you ran the selenium functionality from direct connect or as a server, not whether you use chrome or firefox.
