### ISSUE TITLE
webdriver-manager update fails on FreeBSD

### ISSUE THREAD

**Issue by ipeshev** [angular/webdriver-manager#248]
No matter version it fails with.
node_modules/webdriver-manager/built/lib/cmds/update.js:111
    binaries[binaries_1.Standalone.id].versionCustom = options[Opt.VERSIONS_STANDALONE].getString();
                                                     ^

TypeError: Cannot set property 'versionCustom' of undefined

**Comment by cnishina** [comment]
BSD is not currently supported.;

**Comment by mackevicius1988** [comment]
When it will be supported?
