### ISSUE TITLE
Syntax error while running conf.js file from Eclipse

### ISSUE THREAD

**Issue by dipakbachhav** [angular/webdriver-manager#249]
C:\Users\User>protractor --version
Version 5.1.1

C:\Users\User>npm --version
3.10.10

C:\Users\User>npm-windows-upgrade
'npm-windows-upgrade' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\User>node -v
v6.10.3

C:\Users\(user)\AppData\Roaming\npm\node_modules\webdriver-manager\built\lib\cli\logger.js:66
info(...msgs) {
^^^
SyntaxError: Unexpected token ...
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (C:\Users\(user)\AppData\Roaming\npm\node_modules\we
bdriver-manager\built\lib\cli\index.js:8:10)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)

**Comment by cnishina** [comment]
I don't think your eclipse is pointed to the right version of node. Version 6 is required by `selenium-webdriver` dependency. The spread token is a node 6 feature. I would try to fix your eclipse settings. I don't know eclipse but its probably a separate configuration to set the node version.

**Comment by dipakbachhav** [comment]
Thank you so much for your valuable reply. 

I can see Windows-->Preferences-->AngularJs->Protractor--> NodeJs Install-->NodejsVersion V4.2.4 
But how to update nodeJs version in eclipse .Can some one help me with the same.

**Comment by cnishina** [comment]
I am not sure. This might be a good question for StackOverflow. There  might be another node user that also uses Eclipse.

**Comment by dipakbachhav** [comment]
@bersling/@Sudharsan Selvaraj  : Can you please help with above issue.

**Comment by dipakbachhav** [comment]
Could you please ask someone to look into it on urgent basis.

**Comment by cnishina** [comment]
@dipakbachhav I'm closing this issue since this is an environment setup with Eclipse and not specific to webdriver-manager. This question might be better asked on StackOverflow.
