### ISSUE TITLE
Set Version for Edge does not work

### ISSUE THREAD

**Issue by chelyuk** [angular/webdriver-manager#256]
`EdgeDriverManager.getInstance().version("3.14393").setup();`
Does not loading previous version of driver. Webdriver manager version is 1.6.2. I have tried to set version for EDGE in few ways with:
`System.setProperty("wdm.edgeVersion", "3.14393")`
and like
```
DesiredCapabilities capabilities = DesiredCapabilities.edge();
capabilities.setVersion("3.14393");
driver = new EdgeDriver(capabilities);
```
Also without success. Though the same option for ChromeDriverManager works properly and correct version of driver binaries loaded.

Looks like that problem in BrowserManager.class line 143 - List<URL> urls = this.getDrivers(); versionToDownload becomes "4.15063" at the moment when version I was set is 3.14393.

In EdgeDriverManager.class function getDrivers() does not provide any options. Line 45
`this.versionToDownload = latestVersion[1];`
Strictly loads only latests version of driver.

**Comment by cnishina** [comment]
Are you sure this issue is for angular/webdriver-manager? What language are you using in the above?

**Comment by cnishina** [comment]
Closing this since this appears off topic to webdriver-manager.
