### ISSUE TITLE
Proxy + update does not work for geckodriver. Please read before adding new issues on this.

### ISSUE THREAD

**Issue by cnishina** [angular/webdriver-manager#257]
I started to write tests for the proxy + update issue that people are noticing. There is an issue with proxy when calling the update command. I am experimenting on a fix but for now, please manually download the file from their [release page on github](https://github.com/mozilla/geckodriver/releases).

**Comment by liaoyunhe** [comment]
After long time trouble shooting, i find this issue.

Any plan to fix the problem?

**Comment by cnishina** [comment]
As a work around, a user could manually set paths to any binary and call update. So `webdriver-manager update --geckoPath=/path/to/geckoDriver --seleniumPath=/path/to/selenium.jar`. The important thing is for webdriver-manager to write the `update-config.json` for people using direct connect or local driver launching with protractor.

Or maybe a user could start webdriver-manager with `webdriver-manager start --geckoPath=/path/to/geckoDriver --seleniumPath=/path/to/selenium.jar --chrome=false`. This could be the override during start.

**Comment by riverd3** [comment]
A update on this issue, 

It seems webdriver-manager does not respect proxy setting as defined in .npmrc.

However if a set http_proxy and https_proxy at OS level, then building will pass.

Can webdriver-manager be updated to respect .npmrc proxy setting?

**Comment by cnishina** [comment]
Closing this issue as duplicate to #257

**Comment by cnishina** [comment]
Closing this issue as duplicate to #189
