### ISSUE TITLE
org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?

### ISSUE THREAD

**Issue by new69** [angular/webdriver-manager#261]
The server is deleting the session before the execute the tests:

16:55:59.804 INFO - Selenium Server is up and running
16:56:10.674 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
16:56:10.706 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome, chromeOptions={args=[--no-sandbox, --headless, --disable-gpu, --window-size=800x600]}}]])
16:56:10.726 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome, chromeOptions={args=[--no-sandbox, --headless, --disable-gpu, --window-size=800x600]}}]
Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 38555
Only local connections are allowed.
16:56:11.292 INFO - Detected dialect: OSS
16:56:11.311 INFO - Done: [new session: Capabilities [{count=1, browserName=chrome, chromeOptions={args=[--no-sandbox, --headless, --disable-gpu, --window-size=800x600]}}]]
16:56:11.332 INFO - Executing: [set script timeout: 11000])
16:56:11.337 INFO - Done: [set script timeout: 11000]
16:56:11.837 INFO - Executing: [get: data:text/html,<html></html>])
16:56:11.847 INFO - Executing: [delete session: 29533bfa-b7d3-4988-87ce-718e3ec7551a])
16:56:11.851 INFO - Done: [get: data:text/html,<html></html>]
16:56:11.865 INFO - Executing: [execute script: window.name = "NG_DEFER_BOOTSTRAP!" + window.name;window.location.replace("https://dk57nqppwurwj.cloudfront.net/#/session/localhost/event/19572?host=prod");, []])
16:56:11.921 INFO - Done: [delete session: 29533bfa-b7d3-4988-87ce-718e3ec7551a]
16:56:12.538 WARN - Exception thrown
org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?

**Comment by cnishina** [comment]
I'm not sure if I can help. Possibly add more information to debug this.

**Comment by cnishina** [comment]
@new69 Ping. Please update this.

**Comment by cnishina** [comment]
It appears that this has been abandoned. Closing.
