### ISSUE TITLE
Bump ChromeDriver version

### ISSUE THREAD

**Issue by ricksmt** [angular/webdriver-manager#262]
Can we bump up the ChromeDriver version? I'd love to use the `--headless` mode with Protractor on my CI server.

**Comment by adiherzog** [comment]
When using `protractor 5.1.2` I get `webdriver-manager 12.0.6` which gives me `chromedriver 2.31` which is the latest one and compatible with Chrome 30. Are you maybe using an older version of protractor?

**Comment by ricksmt** [comment]
Ah, you're totally correct. Didn't realize I needed to update protractor first. Thanks!
