### ISSUE TITLE
Need to support "-enablePassThrough false" for selenium standalone server

### ISSUE THREAD

**Issue by bliss7** [angular/webdriver-manager#265]
It seems that recent version of selenium standalone server introduced new feature of "pass through mode". when it's enabled, selenium standalone server doesn't pass argument for phantomjs correctly via phantomsjs.cli.args. It is working as well with passing "-enablePassThrough false" to selenium standalone server.

https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG#L24-L29

**Comment by bliss7** [comment]
I'm using phantomjs via protractor something like the following:

```
webdriver-manager start &

protractor protractor.conf
````

protractor.conf has a configuration like the following:
```
{
   ...,
   multiCapabilities: [{
      browserName: 'phantomjs',
      'phantomjs.cli.args': [ '--ignore-ssl-errors=true' ],
      ...
   }],
   ...
}
```

**Comment by cnishina** [comment]
So PhantomJS is no longer being supported ("abandoned"). Please see: https://github.com/ariya/phantomjs/issues/15105. I would suggest using headless Chrome.

Protractor config with headless Chrome.
```
{
  browserName: 'chrome',
  chromeOptions: {
    args: ['--headless']
  }
}
```

Unless there is another reason to have this feature, I think we should close this feature request.

**Comment by krukru** [comment]
Is it in any way possible to pass custom args to webdriver-start, which would get passed to selenium. Passing `enablePassThrough false` to java when running selenium.jar is the recommended approach to getting tests running on non-chrome browsers (along with downgrading selenium to some particular version).
