### ISSUE TITLE
The update command does not indicate what to do when rate limit reached

### ISSUE THREAD

**Issue by benjaminapetersen** [angular/webdriver-manager#270]
Given:

```bash
$ webdriver-manager update
webdriver-manager: using global installed version 12.0.6
(node:48495) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/webdriver-manager/selenium/chromedriver_2.32.zip'
(node:48495) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Failed to make Github request, rate limit reached.
```

It would be helpful to provide suggestions for what the user can do as a next step.

**Comment by cnishina** [comment]
I agree here. GeckoDriver grabs information from GitHub and the APIs are rate limited for non authenticated requests. We try our best to make unnecessary requests; however, the error message does not provide any insight on how long to wait or where to look at the documentation what the rate limit is.

**Comment by benjaminapetersen** [comment]
Error is from [this file](https://github.com/angular/webdriver-manager/blob/77491ce28df2fdcd2bfd3b6797ff2db46f4b37c3/lib/binaries/config_source.ts#L186).

Suggestions for improving this that follows previous conventions for similar issues?

**Comment by benjaminapetersen** [comment]
Any insight into how to workaround?  Even just to get some details going on this issue.  I find that the rate limit problem does not go away
`
(node:64146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to make Github request, rate limit reached.
`

**Comment by benjaminapetersen** [comment]
FWIW this continues to be an enigma.  Created a new `hello-world` angular1.5 app w/grunt/karma/protractor all latest just to kick the tires and see if I could solve the problem I was having in an older repo and ended up getting a lot of the same issues (after it ran perfectly fine for a while).  

Output ends up:

```bash 
[15:43:57] I/testLogger - [firefox #01] PID: 53192
[firefox #01] [15:43:57] E/local - Error code: 135
[firefox #01] [15:43:57] E/local - Error message: No update-config.json found. Run 'webdriver-manager update' to download binaries.
[firefox #01] [15:43:57] E/local - Error: No update-config.json found. Run 'webdriver-manager update' to download binaries.
[firefox #01]   at IError (~/github/lunch-and-learn-grunt-testing-angular/node_modules/protractor/built/exitCodes.js:6:1)
[firefox #01]   at ProtractorError (~/github/lunch-and-learn-grunt-testing-angular/node_modules/protractor/built/exitCodes.js:11:9)
[firefox #01]   at BrowserError (~/github/lunch-and-learn-grunt-testing-angular/node_modules/protractor/built/exitCodes.js:52:9)
[firefox #01]   at Local.addDefaultBinaryLocs_ (~/github/lunch-and-learn-grunt-testing-angular/node_modules/protractor/built/driverProviders/local.js:41:23)
[firefox #01]   at Local.setupDriverEnv (~/github/lunch-and-learn-grunt-testing-angular/node_modules/protractor/built/driverProviders/local.js:82:14)
[firefox #01]   at Local.setupEnv (~/github/lunch-and-learn-grunt-testing-angular/node_modules/protractor/built/driverProviders/driverProvider.js:111:34)
[firefox #01]   at q.then (~/github/lunch-and-learn-grunt-testing-angular/node_modules/protractor/built/runner.js:335:41)
[firefox #01]   at _fulfilled (~/github/lunch-and-learn-grunt-testing-angular/node_modules/q/q.js:834:54)
[firefox #01]   at self.promiseDispatch.done (~/github/lunch-and-learn-grunt-testing-angular/node_modules/q/q.js:863:30)
[firefox #01]   at Promise.promise.promiseDispatch (~/github/lunch-and-learn-grunt-testing-angular/node_modules/q/q.js:796:13)
[firefox #01]   at ~/github/lunch-and-learn-grunt-testing-angular/node_modules/q/q.js:857:14
[firefox #01]   at runSingle (~/github/lunch-and-learn-grunt-testing-angular/node_modules/q/q.js:137:13)
[firefox #01]   at flush (~/github/lunch-and-learn-grunt-testing-angular/node_modules/q/q.js:125:13)
[firefox #01]   at _combinedTickCallback (internal/process/next_tick.js:73:7)
[firefox #01]   at process._tickCallback (internal/process/next_tick.js:104:9)
[firefox #01]
```
Is a bit bewildering.  I have tried:

```
webdriver-manager update
./node_modules/protractor/bin/webdriver-manager update
npm run update-webdriver // which just calls the above
```
I'll get similar things over and over:

```
> lunch-and-learn-grunt-testing-angular@0.0.1 update-webdriver-local ~/github/lunch-and-learn-grunt-testing-angular
> ./node_modules/protractor/bin/webdriver-manager update

[15:43:47] I/update - chromedriver: file exists ~/github/lunch-and-learn-grunt-testing-angular/node_modules/webdriver-manager/selenium/chromedriver_2.32.zip
[15:43:47] I/update - chromedriver: unzipping chromedriver_2.32.zip
[15:43:48] I/update - chromedriver: setting permissions to 0755 for ~/github/lunch-and-learn-grunt-testing-angular/node_modules/webdriver-manager/selenium/chromedriver_2.32
[15:43:48] I/update - chromedriver: chromedriver_2.32 up to date
(node:53170) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to make Github request, rate limit reached.
[15:43:48] I/update - selenium standalone: file exists ~/github/lunch-and-learn-grunt-testing-angular/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.5.3.jar
[15:43:48] I/update - selenium standalone: selenium-server-standalone-3.5.3.jar up to date
```

**Comment by benjaminapetersen** [comment]
Looks related to #216

**Comment by benjaminapetersen** [comment]
Would it be possible to provide some information about how to manually resolve the issue?  IE, via browser, what to go download, where to put it, etc.  Its not a pretty solution, but would be a potential workaround.

**Comment by benjaminapetersen** [comment]
Possible to hard-code a fallback version if the request fails due to rate limiting?  This does create some developer maintenance for future releases, but improves the user experience.

**Comment by benjaminapetersen** [comment]
Still see this:

```

[14:44:40] I/file_manager - creating folder ~/web-console/node_modules/protractor/node_modules/webdriver-manager/selenium
(node:99759) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to make Github request, rate limit reached.
[14:44:41] I/update - chromedriver: unzipping chromedriver_2.33.zip
[14:44:41] I/update - chromedriver: setting permissions to 0755 for ~/web-console/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.33
```

I'd consider constructing a PR if the above suggestion is acceptable?  It would add some maintenance overhead to updating a fallback version.  If no, +1 to a discussion about alternative approaches.

**Comment by elgohr** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1425706

**Comment by joshua-s** [comment]
Is there any progress on this?

**Comment by dandye** [comment]
My work around is to:
1. cache the file `node_modules/webdriver-manager/selenium/gecko-response.json` (this is the GitHub API response)
2. `touch` it, so that it is less than 1hr old

`webdriver-manager` will then use that file instead of making the problematic Unauthenticated GitHub API Request.

The rationale for caching is described in the bugzilla link above: [Document best practices for deploying geckodriver in README](https://bugzilla.mozilla.org/show_bug.cgi?id=1425706):
> * cache dependencies. Major CI providers will all provide some way
> to cache downloaded artifacts, and since geckodriver is rarely
> updated and updates are typically not essential and may even be
> problematic, it seems like a good fit for caching. It might not
> improve performance since the CI caches themselves will also
> involve some remote download, but it will certainly avoid rate
> limits.

**Comment by cnishina** [comment]
Done! Version 13 has a github token flag. No more rate limit issues (hopefully)
