### ISSUE TITLE
webdriver-manager, process stopped after "Starting Selenium server"

### ISSUE THREAD

**Issue by bisonier** [angular/webdriver-manager#272]
Windows 10/Server 2008 R2
node 6.11.3
npm 5.3.0
grunt-cli v1.2.0
protractor 5.1.2

Started by grunt:
`...
        protractor_webdriver: {
            options: {
                path: 'node_modules/protractor/bin/',
                command: 'webdriver-manager start --verbose --proxy http://<url>:8080',
                keepAlive: true,
            },
            start: {
            },
        },
...`
the same config on two systems, one Windows 10 (W10, working), one Windows 2008 R2 (W2008, not working).
On the W10, after "Starting Selenium server", a java process is started, and "Started Selenium server: <url>:4444"  is shown
On the W2008, the webdriver-manager process is exited without starting java, and the initiating grunt process waits forever.

when webdriver-manager is started manually on W2008, the selenium server is starting:
`$ webdriver-manager start
[16:28:51] I/start - java -Dwebdriver.chrome.driver=C:\guiBuild\npm6.11.3\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.32.exe -Dwebdriver.gecko.driver=C:\guiBuild\npm6.11.
3\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodriver-v0.18.0.exe -jar C:\guiBuild\npm6.11.3\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.5.3.jar -port 4444
[16:28:51] I/start - seleniumProcess.pid: 12416
16:28:52.343 INFO - Selenium build info: version: '3.5.3', revision: 'a88d25fe6b'
16:28:52.344 INFO - Launching a standalone Selenium Server
2017-09-15 16:28:52.378:INFO::main: Logging initialized @511ms to org.seleniumhq.jetty9.util.log.StdErrLog
16:28:52.443 INFO - Driver class not found: com.opera.core.systems.OperaDriver
16:28:52.506 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform VISTA
16:28:52.541 INFO - Using the passthrough mode handler
2017-09-15 16:28:52.575:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-09-15 16:28:52.608:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@4b4523f8{/,null,STARTING} has uncovered http methods for path: /
2017-09-15 16:28:52.620:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@4b4523f8{/,null,AVAILABLE}
2017-09-15 16:28:52.810:INFO:osjs.AbstractConnector:main: Started ServerConnector@5f282abb{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-09-15 16:28:52.811:INFO:osjs.Server:main: Started @944ms
16:28:52.811 INFO - Selenium Server is up and running
`

Even with --verbose, there is no output why the java process is not started

**Comment by cnishina** [comment]
I am not familiar with the `keepAlive: true` command. My thoughts on this is that it is is something to do with the grunt command. Have you verified that this doesn't work if you just call the command `node node_modules/protractor/bin/webdriver-manager start`?

**Comment by bisonier** [comment]
Ok, multiple problems:
Answer to my last statement: when started by a grunt task, --verbose must be added to the starting grunt task, not only to the call of webdriver-manager
Then i could read the messages.
keepAlive is an option of grunt-protractor-webdriver: "Whether or not to keep the Selenium server process alive when no more browser session are connected." Should not affect my problem.
I think my orignal problem was the proxy not working with a "home call (one of chromedriver.storage.googleapis.com:443
api.github.com:443
selenium-release.storage.googleapis.com:443)" of the started webdriver. Now it works, thanks.
