### ISSUE TITLE
Use Chromium's available versions to find the stable version of ChromeDriver

### ISSUE THREAD

**Issue by benjaminapetersen** [angular/webdriver-manager#280]
It would be most helpful if configuration could be committed to code (and then version control).  Simply put, I'd like to be able to assert versions in `package.json` or a `webdrivermanager.json` config file.  Running `webdriver-manager update` & getting whatever drivers & version of selenium happens to install is concerning as it makes it difficult to trust the e2e setup (did a version change, or was it a test flake?).  I realize you can pass flags to `webdriver-manager`.  Thats a good start, but perhaps one more layer of polish?

**Comment by cnishina** [comment]
You could pass flags to control the versions being downloaded. Also this is well documented in the repo. I'm not exactly sure what this extra layer would do.

**Comment by cnishina** [comment]
I think a webdrivermanager.json could be interesting. Kind of like freezing the dependencies like a npm lock on binaries. I do not have the bandwidth to get this done any time soon...

**Comment by cnishina** [comment]
I think a webdrivermanager.json could be interesting. Kind of like freezing the dependencies like a npm lock on binaries. I do not have the bandwidth to get this done any time soon...

**Comment by cnishina** [comment]
I think a webdrivermanager.json could be interesting. Kind of like freezing the dependencies like a npm lock on binaries. I do not have the bandwidth to get this done any time soon...

**Comment by benjaminapetersen** [comment]
Exactly.

Is tempting to look, but I'd prob hesitate to take a stab @ a PR w/o some suggested direction from anyone more core to the project.

**Comment by cnishina** [comment]
This seems reasonable to read a file and use this file for versions. Maybe this could also be tied into pinning a version. So webdriver-manager might have a default version json file (at least to pin chromedriver to the version 73) and a user can define their own webdriver-manager json file.

When 74 is released, we will need to remove the pinned version from the repo and let users define their own json file. This could just be used just in case we run into the current chrome + chromedriver version mismatch.

**Comment by cnishina** [comment]
From a previous comment in #306:

> we will support a config file for pinning downloads and also starting the server. Instead of checking the file for the last version downloaded we could refer to the config first

**Comment by cnishina** [comment]
I like having a configuration code in the repo but I also think it could be high maintenance. I just needed to release of the legacy branch to 12.1.5 because Chrome 75 came out. Maybe we could think of a better way to do this.

**Comment by cnishina** [comment]
New idea.... we download the Chromium information, find the smallest version which (I think) is the stable version. So then we can download that ChromeDriver which should match most peoples Chrome versions.

So that's probably what should happen here and we should document this so this is no longer a big issue. Still should be marked as P0 although the action item is different. Will update the title.

**Comment by cnishina** [comment]
Closing this bug in favor of #410. I might have duplicated the bug and plan to keep the latest since it has some work there.
