### ISSUE TITLE
--out_dir doesn't honor relative paths

### ISSUE THREAD

**Issue by josepmc** [angular/webdriver-manager#286]
When using the flag '--out_dir' and setting it to a relative path (e.g. in package.json), the flag won't honor the relative path (instead it will use as 'base directory' the webdriver-manager installation).

Also, if you try to wrap the webdriver-manager installation within an execSync it won't finish under Windows installations.

**Comment by cnishina** [comment]
Please provide more information what you are trying to do, what version you are using, etc.

**Comment by josepmc** [comment]
When you're using `webdriver manager update --out_dir='./mydir'` or `webdriver manager update --out_dir='mydir'` the path is not being calculated based on process.cwd but instead on __dirname. This makes it happen inside the webdriver-manager directory instead of where it's supposed to do.

*Why is this a problem?*
This becomes a problem when used in a 'package.json' file, as then you're forced to wrap the webdriver-manager call in another script so as to calculate the absolute path.

*Which extra problems does this flag yield?*
- Running webdriver-manager in a wrapper makes it not ever exit under Windows. After 'Initialization complete' (if you're using Android) it will stay there for hours without finishing.

- This flag doesn't avoid the following files from being written in the default selenium dir:
`
- chrome-response.xml
- gecko-response.json
- standalone-response.xml
`

- This flag also conflicts with Protractor (to the point of making protractor not work when used). Protractor uses the following in direct.ts (taken from the compiled code):
`
const SeleniumConfig = require('webdriver-manager/built/lib/config').Config;
let updateJson = path.resolve(SeleniumConfig.getSeleniumDir(), 'update-config.json');
`
And webdriver-manager is always providing the same 'SeleniumConfig' path, that is:
`
return path.resolve(Config.dir, '..', '..', 'selenium/');
`

This will make installations done outside the 'default' dir fail. A possible workaround would be to use:
`
return process.env.SELENIUM_DIR ||  path.resolve(Config.dir, '..', '..', 'selenium/');
`

The version used is 12.0.6.

**Comment by cnishina** [comment]
Could you try this again? I rewrote this for version 13. I'll leave this open since out_dir works for the use case for Protractor 6. Let me know. Thanks!

**Comment by cnishina** [comment]
The default for the download location is: https://github.com/angular/webdriver-manager/blob/master/lib/provider/provider.ts#L5

By default these are set in the provider. So for geckodriver, it is set here: https://github.com/angular/webdriver-manager/blob/master/lib/provider/geckodriver.ts#L22

However, it is overridden here: https://github.com/angular/webdriver-manager/blob/master/lib/provider/geckodriver.ts#L43 based on a config.

And is used https://github.com/angular/webdriver-manager/blob/master/lib/provider/geckodriver.ts#L65

If the path was relative, this should work now. So something llke:

```
vwebdriver-manager update --out_dir foo
curl -o /usr/local/google/home/cnishina/foo/chromedriver.xml https://chromedriver.storage.googleapis.com/
curl https://api.github.com/rate_limit -H "User-Agent: angular/webdriver-manager"
curl -o /usr/local/google/home/cnishina/foo/selenium-server.xml https://selenium-release.storage.googleapis.com/
curl -o /usr/local/google/home/cnishina/foo/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
curl -o /usr/local/google/home/cnishina/foo/selenium-server-standalone-3.141.59.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
curl -o /usr/local/google/home/cnishina/foo/geckodriver.json https://api.github.com/repos/mozilla/geckodriver/releases -H "User-Agent: angular/webdriver-manager"
curl -o /usr/local/google/home/cnishina/foo/geckodriver-v0.24.0-linux64.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
```

Going to close this issue as resolved.

**Comment by josepmc** [comment]
I can confirm it does work now. However, the configuration files are still stored using absolute paths - I have a fork that does fix this though.

**Comment by cnishina** [comment]
If you specify a out_dir path, it can use relative paths as input and it should use absolute paths for any json file it creates as metadata for the binary.
