### ISSUE TITLE
error TS2365: Operator '==' cannot be applied to types 'string | string[]' and 'number'.

### ISSUE THREAD

**Issue by macroking** [angular/webdriver-manager#290]
Node Version: 8.7.0
NPM Version: 4.1.1
TypeScript: 2.3.4
OS: Windows

https://github.com/angular/webdriver-manager/blob/77491ce28df2fdcd2bfd3b6797ff2db46f4b37c3/lib/binaries/config_source.ts#L185

Running tsc throws the following error,

> lib/binaries/config_source.ts(185,50): error TS2365: Operator '==' cannot be applied to types 'string | string[]' and 'number'.

**Comment by mariohmol** [comment]
Having something similar when having `array.length === 0`

**Comment by mariohmol** [comment]
Having something similar when `array.length === 0`

**Comment by macroking** [comment]
Looks like https://github.com/angular/webdriver-manager/pull/297 has a fix for this issue.

**Comment by cnishina** [comment]
Closed with f17b226342173e59b4d2fac54632185c26ca7086
