### ISSUE TITLE
webdriver-manager update problem

### ISSUE THREAD

**Issue by cxm1011** [angular/webdriver-manager#298]
Recently,I start studying  protractor test.But when I use webdriver-manager update command .It will get next errors:
> _C:\Users\chen>webdriver-manager update
> webdriver-manager: using global installed version 12.0.5
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: read ECONNRESET
>     at _errnoException (util.js:1024:11)
>     at TLSWrap.onread (net.js:615:25)_

It will update success sometimes.But most of time  it will update failure.I have try many methods but have no effective.
I  am very happy you can give me some advice.

**Comment by npavangouda** [comment]
Even I am having the same issue. Did you solve this?

**Comment by cnishina** [comment]
Closing this issue. I addressed these issues in version 13. If this is still happening, please create a new issue.
