### ISSUE TITLE
killing "webdriver-manager start" process leaves orphaned "java" process on Windows

### ISSUE THREAD

**Issue by anurse** [angular/webdriver-manager#299]
Repro steps:

1. Run `webdriver-manager start`
2. Launch [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer)
3. Note the process ID of `java.exe`:

![image](https://user-images.githubusercontent.com/7574/35949084-aa344dd2-0c24-11e8-9915-d59b42ef5593.png)

4. Kill the node process associated with `webdriver-manager`

![image](https://user-images.githubusercontent.com/7574/35949096-b6cad9c6-0c24-11e8-982c-fab160ed9124.png)

Expected behavior:

`node.exe` **and** the associated `java.exe` are no longer running.

Actual behavior:

The associated `java.exe` is still running, now orphaned (with no parent).

![image](https://user-images.githubusercontent.com/7574/35949121-d4ad8f88-0c24-11e8-83d9-bb387f2a1476.png)

This occurs because the `spawn` util is launching processes in `cmd.exe`. Unfortunately, it's a long standing known issue with `cmd.exe` that when terminated it does not terminate child processes. This can be fixed by launching `java.exe` directly (similarly with other executables).

https://github.com/angular/webdriver-manager/blob/7dbc1dfbccc60c8836e7c1d390fd5562e0af5b9d/lib/utils.ts#L20-L27

`webdriver-manager shutdown` seems to have no effect as well.

**Comment by cnishina** [comment]
We start java.exe on Windows. This has been fixed.
