### ISSUE TITLE
webdriver-manager update --ignore_ssl: TypeError: Cannot set property 'msg' of null

### ISSUE THREAD

**Issue by teamco** [angular/webdriver-manager#301]
TypeError: Cannot set property 'msg' of null
    at fs.stat (C:\Users\Timnav\AppData\Roaming\npm\node_modules\webdriver-manager\built\lib\files\downloader.js:53:47)
    at FSReqWrap.oncomplete (fs.js:167:5)

**Comment by cnishina** [comment]
Closing as obsolete. This has been addressed though.

**Comment by cnishina** [comment]
This should not happen anymore because we do not attach a msg to an error object. See https://github.com/angular/webdriver-manager/blob/master/lib/provider/utils/http_utils.ts#L227

**Comment by jakehockey10** [comment]
@cnishina If this isn't supposed to happen anymore, I'm not sure how to diagnose when it IS still happening?  I have a brand new Angular 9 CLI application, nothing else added to it.  And I receive this error when I run `ng e2e` locally.  Any ideas how to diagnose this?
