### ISSUE TITLE
ChromeDriver 2.37 does not run Selenium Tests on the latest chrome Version 65.0.3325.181 

### ISSUE THREAD

**Issue by cdcrazy2292** [angular/webdriver-manager#308]
Hi, chrome automatically updated itself. I am running selenium tests and ran the command 
`webdriver-manager update`

Everything works fine up until I start a test. 
When a test runs and chrome opens, it stays stall. It doesn't run at all. The URL bar has this as the url address: data:,

There are no errors in the logs. 

![seleniumchromefailure](https://user-images.githubusercontent.com/6739273/38689302-3b8012e8-3e49-11e8-86dc-faddc8acf16b.png)

It will be nice if I get some help. 
Thanks.

**Comment by macroking** [comment]
@cdcrazy2292 I think SO is the best place for this question. 
PS: I also use chromedrive2.7 [ Windows ] and no issue what so ever.

**Comment by cdcrazy2292** [comment]
@macroking  Hi thanks for replying. I've tried SO, however like I said, it's happening for after the latest update. I made no changes to the project. The only thing was updating chromedriver and chrome. After that nothing runs. 

You meant to say you are running version 2.37 and not 2.7 right
??

**Comment by macroking** [comment]
@cdcrazy2292 My bad, that is a typo

**Comment by cnishina** [comment]
I am going to close this issue. There is a new codebase out for webdriver-manager. Does this fix the chromedriver / chrome issue? I am not sure. This could be a chrome version and chromedriver version mismatch. Please refer to the chromedriver chromium website.
