### ISSUE TITLE
Not able to fetch correct Version for Edge Driver 

### ISSUE THREAD

**Issue by aaravgotra** [angular/webdriver-manager#315]
local_driver = webdriver.Edge(EdgeDriverManager(version='3.14393').install())
Not able to fetch specified edge driver version(3.14393). 

Version Details---
webdriver_manager==1.6.0
Selenium == 3.11
Python == 2.7

**Comment by cnishina** [comment]
Because EdgeDriver can be installed in many different places, the flag on the command line is to help locate the EdgeDriver location. It should not install or download the binary. This is currently as designed.
