### ISSUE TITLE
Element not focused

### ISSUE THREAD

**Issue by nilsroesel** [angular/webdriver-manager#323]
While creating e2e tests i recognized, that the protractor doesent send the keys to <select> sometimes.
The tests failed with this problem after some update from the webdriver manager , but i dont know extactly which one.(thats why i report this at first here, maybe if you guys are saying this is a protractor issue it could also be there reported)

**Comment by nilsroesel** [comment]
For anyone maybe having the same problem i want to share with you my workaround:
i overrode the sendKeys method on the WebElement prototype inside the protractor config onPrepare() like this to get the focus everywhere without having to fix it everywhere.
```javascript
onPrepare: function() {
    const fn =  protractor.WebElement.prototype.sendKeys;
    protractor.WebElement.prototype.sendKeys = function (input) {
            this.click();
            return fn.apply(this, arguments);
    };
}
```

**Comment by cnishina** [comment]
Closing this.

This should probably be posted to Protractor. Webdriver-manager just downloads binaries and starts a selenium server. If this a functional issue with a driver, you should report it to the driver itself.

**Comment by cnishina** [comment]
Looking at your `sendKeys` override, I usually click on a box before sending keys because it might not be a focused input.

**Comment by nilsroesel** [comment]
yeah, but simetimes it says then the element is not clickable even if its present, it took me hours to figure that focusing thing out, because it was sometimes depending on the window resolution.
I'll post this to the chrome driver guys, because this were never an issue before to me, so i think its no protractor issue itself. tnaks for the help here 👍
