### ISSUE TITLE
Provide a way to change Selenium standalone logging level

### ISSUE THREAD

**Issue by pawelus** [angular/webdriver-manager#324]
Selenium 3.10 changed logging level of many protocol messages from INFO to FINE many debugging messages (see [commit](https://github.com/seleniumhq/selenium/commit/78bece338aa74c5e3bacfa1aa403e423d6a3d286)).

It's useful to see those messages during debugging sessions, but to be able to see them one has to pass `-Dselenium.LOGGER.level=FINE` when starting standalone server.

Currently there's no way to do this in webdriver-manager.

Please provide a way to set selenium.LOGGER.level to any value (e.g. by a command line switch)

**Comment by cnishina** [comment]
This is a great feature idea! Thanks for pointing this out.
