### ISSUE TITLE
webdriver jettyThreads option

### ISSUE THREAD

**Issue by archagy** [angular/webdriver-manager#330]
Recently from jenkins I was getting this error.

`01:34:25 [01:34:25] 01:34:25.560 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
01:34:25 
01:34:25 [01:34:25] Exception in thread "main" 
01:34:25 [01:34:25] java.lang.IllegalStateException: Insufficient configured threads: required=3 < max=3 for QueuedThreadPool[qtp1734161410]@675d3402{STARTED,3<=3<=3,i=3,q=0}[ReservedThreadExecutor@1c93084c{s=0/1,p=0}]
01:34:25 [01:34:25] 
01:34:25 
01:34:25 [01:34:25] 	at org.seleniumhq.jetty9.util.thread.ThreadPoolBudget.check(ThreadPoolBudget.java:155)`

I could solve it adding on the build/lib/start.js ->start function the option to set the jettyThreads value.

I don't know if there are other way to add it or other way to solve my original problem (lol)
but at least it's working and running my tests well.

P.S if this option is helpful I could try to add the change on a PR.

**Comment by kevinip-zingbox** [comment]
Hello @archagy , I've been having this issue on webdriver-manager as well recently. Seems like other people are encountering this as well. https://forum.gitlab.com/t/insufficient-configured-threads-selenium-standalone-chrome/20594

I've been trying to find the file to configure threads as that is what forums are saying and what you have done. Can you elaborate on your solution?

**Comment by archagy** [comment]
Hi @kevinip-zingbox , I don't know why the error occurs but here is what I did to solve it.

Go to your node_modules/webdriver-manager folder and search the start.js file.
current path:
>node_modules/webdriver_manager/built/lib/cmds/start.js

After the line 213 I add the next code

`args.push('-jettyThreads', 512);`

That solve my problem, I hope solve your problem as well.

**Comment by kevinip-zingbox** [comment]
@archagy Thank you for the quick reply with your solution. I'm just running UI tests on my machine. I worked around my problem by installing 'selenium-standalone'.

> npm install -g selenium-standalone

then

> selenium-standalone install

Then I tried running the UI tests as normal and they ran fine.

I'll try to reproduce your solution tomorrow and will comment below
Thanks for your help archagy!

**Comment by kevinip-zingbox** [comment]
@archagy Seems they updated Selenium server today. After updating to Selenium server version: 3.141.5, I was able to bring up the Selenium server through webdriver-manager again.

I added the line you specified and was able to bring up the server. Then I took out the line and was able to bring the server up this way as well. So it seems the line is not needed anymore.

> / Add the port parameter, has to declared after the jar file
           if (seleniumPort) {
               args.push('-port', seleniumPort);
           }
           **args.push('-jettyThreads', 512);**
           let argsToString = '';
           for (let arg in args) {
               argsToString += ' ' + args[arg];
           }

It seems to be working as it did before. It solved my problem at least. Thanks again.

**Comment by archagy** [comment]
@kevinip-zingbox 
Great news, I didn't test it yet but for now I will close the issue.

Thanks for keep it up this error.
