### ISSUE TITLE
Make an authenticated request to Github

### ISSUE THREAD

**Issue by ofk** [angular/webdriver-manager#340]
I often see the following:

```
$ webdriver-manager update
(node:3480) UnhandledPromiseRejectionWarning: Error: Failed to make Github request, rate limit reached.
```

Because, webdriver-manager make https://api.github.com/repos/mozilla/geckodriver/releases requesting without authentication.
In my environment, the request returns the following results:

```
{
  "message": "API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

Therefore, I want to give `?client_id=<client_id>&client_secret=<client_secret>` to https://github.com/angular/webdriver-manager/blob/master/lib/binaries/gecko_driver_github.ts#L10 .

**Comment by cnishina** [comment]
You are correct. There is a fix. Look at the 13.0.0-beta release. It is currently paired with Protractor 6.0.0-beta. Closing this since it has already been addressed.
