### ISSUE TITLE
adm-zip uses GPL code so is not MIT licensed

### ISSUE THREAD

**Issue by TerryAspen** [angular/webdriver-manager#341]
The adm-zip library that is a dependency of this library has a long outstanding issue (#77) that it contains the deflater.js file which is GPL licensed.  I do see a recent commit in adm-zip that looks like it resolves this GPL issue but the webdriver-manager should reference this newer adm-zip.

**Comment by cnishina** [comment]
I just checked that we use the latest in the last audit. Closing this issue.
