### ISSUE TITLE
Downloader.ts does not handle error properly

### ISSUE THREAD

**Issue by lucianoac** [angular/webdriver-manager#347]
I´m not sure how to reproduce this issue, but it seem to be a simple bug:

https://github.com/angular/webdriver-manager/blob/beeaae6aeac050e17217824945ec7b912647532d/lib/files/downloader.ts#L75

I´m getting a 'Cannot set property 'msg' of null' when running the code coming from this line. I´m not sure what is the best solution, but the bug looks pretty simple: there is a "if + return" a few lines above testing if the error object exists. If error is null or undefined it goes through the next statement trying to assign something to the msg attribute.

**Comment by cnishina** [comment]
This is completely changed. This is no longer how files get downloaded. Closing this. 😀
