### ISSUE TITLE
Webdriver-manager unable to detect selenium standalong jar. 

### ISSUE THREAD

**Issue by skAutomation12** [angular/webdriver-manager#348]
I/testLogger - [phantomjs #01-0] PID: 24640

[phantomjs #01-0] [12:04:53] E/local - Error code: 135
[phantomjs #01-0] [12:04:53] E/local - Error message: No selenium server jar found at C:\\node_modules\selenium-server-standalone-jar\jar\selenium-server-standalone.jar. Run 'webdriver-manager update' to download binaries.

But I see Selenium standalong jar in the above directory.

**Comment by cnishina** [comment]
It also required the update config json file. Please try again with the latest release and read the changelog. Closing issue.
