### ISSUE TITLE
Web driver manager is not taking latest chrome driver version 73.0.3683.68

### ISSUE THREAD

**Issue by lakshmi-236** [angular/webdriver-manager#356]
web driver manager is not taking latest chrome driver version. Even though 73.0.3683.68 is the latest one it takes chrome driver 2.46 .

**Comment by cnishina** [comment]
2.46 is the old version scheme. ChromeDriver 73.0.3683.68 and it currently is downloading the beta version. Appears to be a duplicate issue: https://github.com/angular/webdriver-manager/issues/353
