### ISSUE TITLE
--seleniumPort is not available in 1.13

### ISSUE THREAD

**Issue by jgrant216** [angular/webdriver-manager#360]
Using 1.12 and passing --seleniumPort=1234 will properly override the default port of 4444.  However, in 1.13, the --seleniumPort=1234 is not being respected.

I see the help text no longer mentions seleniumPort as an option.  The change log does not mention its removal.

Example using 1.13
webdriver-manager start --seleniumPort=56390
/Library/Java/jdk1.8.0_171.jdk/bin/java -Dwebdriver.chrome.driver=null -Dwebdriver.gecko.driver=null -jar  -port 4444

Example using 1.12
webdriver-manager start --seleniumPort=56390
/Library/Java/jdk1.8.0_171.jdk/bin/java -Dwebdriver.chrome.driver=null -Dwebdriver.gecko.driver=null -jar  -port 56390

If I take the java command and run it specifying my override port on 1.13, I get the following which claims to start selenium on the port I wanted but then errors with 4444...
+ java '-Dwebdriver.chrome.driver=D:\views\jenkins-workspace\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS_11.5.0\node_modules\webdriver-manager\downloads\chromedriver_73.0.3683.68.exe' '-Dwebdriver.gecko.driver=D:\views\jenkins-workspace\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS_11.5.0\node_modules\webdriver-manager\downloads\geckodriver_0.24.0.exe' -jar 'D:\views\jenkins-workspace\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS_11.5.0\node_modules\webdriver-manager\downloads\selenium-server-standalone-3.141.59.jar' -role node -servlet org.openqa.grid.web.servlet.LifecycleServlet -registerCycle 0 -port 56390
14:04:42.395 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
14:04:42.760 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 56390
14:04:43.173 INFO [SelfRegisteringRemote.addExtraServlets] - binding org.openqa.grid.web.servlet.LifecycleServlet to /extra/LifecycleServlet/*
2019-04-12 14:04:43.300:INFO::main: Logging initialized @1699ms to org.seleniumhq.jetty9.util.log.StdErrLog
14:04:44.022 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
14:04:44.263 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 56390
14:04:44.264 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
14:04:46.760 WARN [SelfRegisteringRemote.registerToHub] - Error getting the parameters from the hub. The node may end up with wrong timeouts.Failed to connect to localhost/0:0:0:0:0:0:0:1:4444
14:04:46.761 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://localhost:4444/grid/register
Exception in thread "main" org.openqa.grid.common.exception.GridException: Error sending the registration request: Failed to connect to localhost/0:0:0:0:0:0:0:1:4444

**Comment by cnishina** [comment]
This should be an easy bug to fix. I did not add this in to the latest.

**Comment by jgrant216** [comment]
@cnishina, can you better describe how this was missed on the release?  Will tests be added to ensure it is not missed again in the future?

**Comment by cnishina** [comment]
It was missed because I rewrote everything and I thought I had moved all the flags over. I think a good way to handle this is to have an issue tracker for the next release to go through old flags and ensure they exist.

**Comment by jgrant216** [comment]
Thank you, @cnishina .  I also noticed version was updated to --version (or the other way around).  The help document was updated so that worked.

The miss in this defect caused us to containerize the test to avoid the port conflicts.  Let's consider it a silver lining!
