### ISSUE TITLE
downloaded chromedriver isn't the latest version

### ISSUE THREAD

**Issue by AleksanderPopov** [angular/webdriver-manager#373]
Hi guys. I'm doint `webdriver-manager update` and see that downloaded version of chromedriver on my macos is 2_46, whenever 73 and 74 already available - http://chromedriver.chromium.org/downloads, and it forces me to manually download latest binary and update it :(

**Comment by bstiles13** [comment]
I would also like to know if webdriver-manager 12.1.1 will support chromedriver 73+ or if an update to 13.0.0 is required

**Comment by cnishina** [comment]
Redirect to full discussion here: https://github.com/angular/protractor/issues/5225

I have backward compatibility support for Protractor 5.4.2 here: https://github.com/angular/webdriver-manager/pull/372.

From Protractor's point of view this isn't a major version bump BUT webdriver-manager 13 removes mobile support for appium and android sdk downloads so I'm not sure how to properly semver Protractor. Should this be 5.5?

**Comment by AleksanderPopov** [comment]
I didn't get it...w-m is a standalone module, which can be downloaded and used separately from protractor, how its related to the fact it does not download latest chrome binaries?

**Comment by vadeneev** [comment]
webdriver manager 13.0.0 works with latest naming of chrome drivers
protractor 5.4.2 shipped with 12.1.1 - probably 12.1.1 doesn't support new naming (latest is 2.46)

**Comment by AleksanderPopov** [comment]
On npm there is 12.1.2, should I use webdriver-manager from a git release instead?

**Comment by cnishina** [comment]
I would hold off for now. I'm going to talk to Julie and Michael what we should do next.

**Comment by duffman03** [comment]
Now it's downloading chrome 75(chromedriver_75.0.3770.8.zip), which seems to be unreleased/beta channel. 

According this bug, we can't override to the correct version:
https://github.com/angular/webdriver-manager/issues/376#issuecomment-487764695

**Comment by cnishina** [comment]
I just can't win today. I'm going to work on this tomorrow. Elevating this to P0. This needs to be fixed for 12.

**Comment by cnishina** [comment]
This has been fixed. See https://github.com/angular/webdriver-manager/issues/376

**Comment by cnishina** [comment]
Closing this issue.
