### ISSUE TITLE
Issue after webdriver-manager update with selenium process id: undefined;  Error: spawn java ENOENT

### ISSUE THREAD

**Issue by prashanthparsi** [angular/webdriver-manager#378]
21:07:42  (node:137) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: response status code is not 200
21:07:42  (node:137) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Pipeline] sh
21:07:44  + npmVersion=0.1.0-prerelease.0
21:07:44  + node_modules/webdriver-manager/bin/webdriver-manager start --detach
21:07:44  java -Dwebdriver.chrome.driver=/home/jenkins/workspace/node_modules/webdriver-manager/downloads/chromedriver_73.0.3683.68 -Dwebdriver.gecko.driver=null -jar /home/jenkins/workspace/node_modules/webdriver-manager/downloads/selenium-server-standalone-4.0.0-alpha-1.jar -role node -servlet org.openqa.grid.web.servlet.LifecycleServlet -registerCycle 0 -port 4444
21:07:44  selenium process id: undefined
21:07:44  events.js:183
21:07:44        throw er; // Unhandled 'error' event
21:07:44        ^
21:07:44  
21:07:44  Error: spawn java ENOENT
21:07:44      at _errnoException (util.js:1022:11)
21:07:44      at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
21:07:44      at onErrorNT (internal/child_process.js:372:16)
21:07:44      at _combinedTickCallback (internal/process/next_tick.js:138:11)
21:07:44      at process._tickCallback (internal/process/next_tick.js:180:9)
21:07:44      at Function.Module.runMain (module.js:686:11)
21:07:44      at startup (bootstrap_node.js:187:16)
21:07:44      at bootstrap_node.js:608:3

**Comment by cnishina** [comment]
Have you tried an older version of the jar file that is not the alpha version?

**Comment by cnishina** [comment]
Okay, when looking up spawn java ENOENT, I get:

> It's an abbreviation of Error NO ENTry (or Error NO ENTity), and can actually be used for more than files/directories.

from https://stackoverflow.com/questions/19902828/why-does-enoent-mean-no-such-file-or-directory

I think you are missing java.

This does not actually appear to be a problem with webdriver-manager itself. I am closing this issue. If you run into a similar issue, I would ask it on stackoverflow. If you feel that webdriver-manager is broken for everyone, feel free to open an issue. Thanks!

**Comment by prashanthparsi** [comment]
When I tried on Friday, this was working. Only after doing the webdriver-manager update, this is broken. I think that is with alpha.
How do I try with non alpha versions? When I did webdriver-manager update, it always downloads the alpha version.

**Comment by prashanthparsi** [comment]
This is the last time when it worked on Friday with version-> selenium-server-standalone-3.141.59.jar

how do i go back to this version?

14:21:30  + npmVersion=0.1.0-prerelease.15
14:21:30  + node_modules/webdriver-manager/bin/webdriver-manager start --detach
14:21:31  java -Dwebdriver.chrome.driver=/home/jenkins/workspace/erformance-ui-automation_develop/node_modules/webdriver-manager/downloads/chromedriver_73.0.3683.68 -Dwebdriver.gecko.driver=null -jar /home/jenkins/workspace/erformance-ui-automation_develop/node_modules/webdriver-manager/downloads/selenium-server-standalone-3.141.59.jar -role node -servlet org.openqa.grid.web.servlet.LifecycleServlet -registerCycle 0 -port 4444
14:21:31  selenium process id: 184
