### ISSUE TITLE
support for custom chromedriver

### ISSUE THREAD

**Issue by duderonomy** [angular/webdriver-manager#382]
Please forgive if this capability already exists but possibly undocumented. 

I need to specify a custom chromedriver binary that is not obtained from Google's chromedriver project repo. 

In my case the a SDK from 2 years ago has a chromedriver binary that I must use for testing. There are no exceptions or workarounds available.  

Can webdriver-manager be used to support a custom chromedriver?

**Comment by cnishina** [comment]
2 years ago would be around chromedriver 2.24? You could download that version with `webdriver-manager update --versions.chrome 2.24` and you could run it with `webdriver-manager start --versions.chrome 2.24`. I am not sure what compatibility issues you might have with the selenium server.

If you need a custom chromedriver binary, you could start it up with the java command. I believe the java command is logged on every `webdriver-manager start`. This means you could specify your own binary and run it yourself.

What you could do: 
In the webdriver-manager start command, specify the --out_dir path to a folder with your binaries and a file with update-config.json file. The update-config.json should have the following:

```
{
  "chrome": {"last": "/full/path/to/chromedriver"},
  "standalone": {"last": "/full/path/to/standalone.jar"}
}
```

Closing this issue. If this is still an issue, please open up an issue on StackOverflow with the webdriver-manager tag. https://stackoverflow.com/questions/tagged/webdriver-manager
