### ISSUE TITLE
session not created: This version of ChromeDriver only supports Chrome version 75

### ISSUE THREAD

**Issue by Allen-Zfu** [angular/webdriver-manager#396]
My chrome version is 
Version 74.0.3729.157 (Official Build) (64-bit)
and I installed the newest version of webdriver-manager. 
Then I got the issue session not created: This version of ChromeDriver only supports Chrome version 75.

Can someone help me out? Really appreciated it.

**Comment by vsravuri** [comment]
@Allen-Zfu 

Which version of Protractor and webdriver you are using?

If you don't want to upgrade to latest Chrome version v75, try `node bin/webdriver-manager update --versions.chrome 74.0.3729.157`

**Comment by Allen-Zfu** [comment]
@vsravuri 
Thank you for replying me. 
The protractor is 5.4.2 and webdriver is 12.1.5.
I tried webdriver-manager update --versions.chrome 74.0.3729.157
but still not working

**Comment by vsravuri** [comment]
@Allen-Zfu What's the error you see when you ran the command?

**Comment by Allen-Zfu** [comment]
@vsravuri 

[13:48:31] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 75
  (Driver info: chromedriver=75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40}),platform=Windows NT 6.1.7601 SP1 x86_64)
[13:48:31] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 75
