### ISSUE TITLE
Wrong ChromeDriver v75 patch version

### ISSUE THREAD

**Issue by carlos-gva** [angular/webdriver-manager#401]
This is quite strange but it seems that webdriver-manager is not downloading the latest version of ChromeDriver, but on the logs, the url is correct:

**Log example**
 ```I/downloader - curl -o/Users/carlos.gouveia/node_modules/webdriver-manager/selenium/chromedriver_75.0.3770.8.zip https://chromedriver.storage.googleapis.com/75.0.3770.90/chromedriver_mac64.zip```

As you can see, two different versions on the same log line.

Is this just a naming issue? Or is it downloading the x.x.x.8 instead of the x.x.x.90 ?

**Comment by carlos-gva** [comment]
@cnishina after trying to force the latest version to be download:
```
webdriver-manager update --versions.chrome=75.0.3770.90
```
The `webdriver-manager start` command started to fail on creating the browser session.

I found that the reason is that even forcing the version, it's still pointing to the previous one (75.0.3770.8).
`I/start - java -Dwebdriver.chrome.driver=/Users/carlos.gouveia/node_modules/webdriver-manager/selenium/chromedriver_75.0.3770.8`

So it seems that webdriver-manager is picking the first v75 version it finds in `chrome-response.xml` instead of the latest one.

**Comment by vsravuri** [comment]
@cnishina 

Though the chrome-response.xml file has both 75.0.3770.8 & 75.0.3770.90, webdriver-manager downloads 75.0.3770.8 instead of 75.0.3770.90

<img width="1260" alt="2019-07-02_1737" src="https://user-images.githubusercontent.com/22808594/60555246-ac669980-9cf0-11e9-94f8-ba1ab9f0f115.png">

**Comment by cnishina** [comment]
If this is happening in webdriver-manager 12, I do not plan to fix this (legacy branch). We are comparing the first 3 sets of digits for semver and the rest was being dropped off. I hope to fix this to the master branch which will eventually be released.

**Comment by denver-HJS** [comment]
@cnishina will this be a new major release of `webdriver-manager` or should we look to find this fix in a different npm package? I'm experiencing something similar where `webdriver-manager` is installing Chrome v74.0.3729.6 even though [Chrome v76.0.3809.68](https://chromedriver.storage.googleapis.com/index.html?path=76.0.3809.68/) is the latest.

**Comment by cnishina** [comment]
I would make sure that you are using the latest webdriver-manager 12.1.6. This should download version 76 of ChromeDriver. I would check the node_modules/webdriver-manager/package.json file to see what version you have installed.

**Comment by denver-HJS** [comment]
@cnishina upgrading to webdriver-manager@12.1.6 did solve my issue. Thank you very much!

**Comment by cnishina** [comment]
@denver-HJS No problem.

Leaving this open because @carlos-gva issue should be looked at. Marking this as a bug.

**Comment by carlos-gva** [comment]
@cnishina I also noticed that when the chromedriver v75.0.3770.140 was released, webdriver-manager started to pull it correctly, I should have updated this issue with that info...
Right now I'm using v12.1.6 and it's all good for Chrome v76.
Many thanks!

**Comment by cnishina** [comment]
This is still not a sustainable way of doing things. Creating #410 to try to address this. Having new PRs and releases is not the right way to do this.
