### ISSUE TITLE
"webdriver-manager update" downloads v75 by default but chrome v76 is now the latest stable version

### ISSUE THREAD

**Issue by tw3** [angular/webdriver-manager#403]
Can "webdriver-manager update" download the driver for v76 by default now?

**Comment by vsravuri** [comment]
@cnishina Chrome v76 is stable version now. webdriver-manager still downloads v75. Could you please provide a new release to address this issue?

**Comment by MathRobin** [comment]
have created a pull request for this https://github.com/angular/webdriver-manager/pull/405

**Comment by Dolly2315** [comment]
Everytime chrome upgrades it stable version , we start getting these kind of issues .Can't we have some proper solution around it

**Comment by tmcconechy** [comment]
is there any way around this temporarily?

**Comment by cnishina** [comment]
For a temporary workaround, you could specify the version of `webdriver-manager update --chrome --max_versions.chrome 76`

**Comment by cnishina** [comment]
Published 12.1.6. Thank you @MathRobin for creating the PR and thank you for creating the issue and discussion.

**Comment by MathRobin** [comment]
Why do you need max version ? At each New version of each browser, you have to change it. Not really easy
