### ISSUE TITLE
webdriver-manager 13 (with protractor 6) downloads wrong Chrome version 

### ISSUE THREAD

**Issue by jimivdw** [angular/webdriver-manager#409]
When running `webdriver-manager update` in version 13.0.0, it downloads chromedriver version 77 (or 77.0.3865.10 to be exact), even though Chrome 77 hasn't had its official release yet (see https://www.chromestatus.com/features/schedule). This causes my Protractor tests to fail with `Error: SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 77`.

The issue does _not_ exist in webdriver-manager 12 (exact version tested: 12.1.6), where it correctly downloads chromedriver 76.0.3809.12.

I know about the workaround of explicitly defining the Chrome version to download (`webdriver-manager update --versions.chrome=76.0.3809.12`), but that isn't really sustainable.

**Comment by cnishina** [comment]
Since Protractor 6 has not landed, we are still tied to webdriver 12.1.6. You could download version 77 with --versions.chrome <chrome version number>. I have limited bandwidth to do this so if you have time, feel free to put in a PR.

**Comment by cnishina** [comment]
Also I would wait on using Protractor 6. We have marked on npm that the latest Protractor is still 5.4.2.

**Comment by cnishina** [comment]
The plan is to release webdriver-manager 13.0.1-beta.1 and not mark it as latest. Hopefully you'll be able to download it with Protractor 6.

**Comment by jimivdw** [comment]
Alright, thanks for the update. I'll hold off on upgrading for now then.

As a side note, passing `--versions.chrome=76` doesn't appear to do anything; only when I specify the exact chromedriver version (`--versions.chrome=76.0.3809.12`) will it download that version.

```
$ ./node_modules/webdriver-manager/bin/webdriver-manager update --versions.chrome=76
curl -o (...)/node_modules/webdriver-manager/downloads/chromedriver.xml https://chromedriver.storage.googleapis.com/
curl https://api.github.com/rate_limit -H "User-Agent: angular/webdriver-manager"
curl -o (...)/node_modules/webdriver-manager/downloads/selenium-server.xml https://selenium-release.storage.googleapis.com/
curl -o (...)/node_modules/webdriver-manager/downloads/chromedriver_mac64.zip https://chromedriver.storage.googleapis.com/77.0.3865.10/chromedriver_mac64.zip
curl -o (...)/node_modules/webdriver-manager/downloads/selenium-server-standalone-4.0.0-alpha-1.jar https://selenium-release.storage.googleapis.com/4.0/selenium-server-standalone-4.0.0-alpha-1.jar
curl -o (...)/node_modules/webdriver-manager/downloads/geckodriver.json https://api.github.com/repos/mozilla/geckodriver/releases -H "User-Agent: angular/webdriver-manager"
curl -o (...)/node_modules/webdriver-manager/downloads/geckodriver-v0.24.0-macos.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-macos.tar.gz


$ ./node_modules/webdriver-manager/bin/webdriver-manager update --versions.chrome=76.0.3809.12
curl -o (...)/node_modules/webdriver-manager/downloads/chromedriver_mac64.zip https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_mac64.zip
curl -o (...)/node_modules/webdriver-manager/downloads/geckodriver-v0.24.0-macos.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-macos.tar.gz
curl -o (...)/node_modules/webdriver-manager/downloads/selenium-server-standalone-4.0.0-alpha-1.jar https://selenium-release.storage.googleapis.com/4.0/selenium-server-standalone-4.0.0-alpha-1.jar
```

**Comment by cnishina** [comment]
12.1.7 should download the latest as per the chromedriver's website with /LATEST_RELEASE. This should be resolved now to always grab the right one.
