### ISSUE TITLE
Missing support for Chrome version 77

### ISSUE THREAD

**Issue by nescalante** [angular/webdriver-manager#420]
Now that Chrome [moved version 77 to stable](https://chromereleases.googleblog.com/2019/09/stable-channel-update-for-desktop.html), Protractor stopped to work in CI with Chrome since most of CIs systems takes stable version.
The issue actually is that webdriver-manager supports [up to version 76](https://github.com/angular/webdriver-manager/commit/c48143c745181d8ea7c37580fa156edaccd71818), and is not compatible with version 77.

```[17:53:12] E/runner - Unable to start a WebDriver session.
(node:6597) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 76
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-101-generic', java.version: '1.8.0_151'
Driver info: driver.version: unknown```

**Comment by TravkinAlex** [comment]
I wonder if 
`webdriver-manager update --versions.chrome 77.0.3865.40`
works as a workaround?

Otherwise it would be great if this repo's maintainers were more active :/
