### ISSUE TITLE
Error: SessionNotCreatedError

### ISSUE THREAD

**Issue by tobias74** [angular/webdriver-manager#443]
Error: SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 80
  (Driver info: chromedriver=80.0.3987.16)

After running "webdriver-manager update" I cannot run my tests anymore. I have looked into similar error reports concerning other versions of chrome, but could not find a working solution.

I was wondering whether I should turn to SO in this matter, but somehow this feels like a bug, so I am reporting it here. Hope this is ok.

Thanks :-)

**Comment by MariaFar** [comment]
I had the same issue yesterday, so I updated [puppeteer](https://github.com/puppeteer/puppeteer/releases/tag/v2.1.1) to support Chrome 80 and now I'm getting this error:
```
[chrome #01-53] [08:33:22] I/direct - Using ChromeDriver directly...
[chrome #01-53] [08:33:22] E/direct - Error code: 135
[chrome #01-53] [08:33:22] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
[chrome #01-53] [08:33:22] E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
```

I have run 'webdriver-manager update' but nothing changed.

**Comment by kernowjoe** [comment]
Im also getting this same issue both locally and on our ci (jenkins)

**Comment by Mumcio** [comment]
The same issue as above.
Updating webdriver manually did not help.

**Comment by MariaFar** [comment]
We downgrade puppeteer and webdriver-manager so they can work with ChromeDriver 79.
As far as we could understand ChromeDriver 80 is not working correctly in Linux.

**Comment by Mumcio** [comment]
@MariaFar they fixed with the latest stable chromedriver version
https://chromedriver.storage.googleapis.com/80.0.3987.106/notes.txt

However I still not working for me.

Can you share google chrome, puppeteer & webdriver-manager versions to use chromedriver 79 ?

**Comment by MariaFar** [comment]
@Mumcio we are using puppeteer v2.0.0, chrome v79.0.3945.36, and webdriver-manager v12.1.7.
our problem was only on Jenkins so we use those commands to update them before the e2e tests.
`webdriver-manager clean && npm i puppeteer@2.0.0 && node ./node_modules/protractor/bin/webdriver-manager update --versions.chrome 79.0.3945.36 --gecko=false --ignore_ssl`

gecko=false = we are not testing in firefox
ignore_ssl = we had some proxy issues

**Comment by tobias74** [comment]
The issue seems to have been resolved. At least for me things are working again after a call to "webdriver-manager update". In case there are no objections I would close this issue now
