### ISSUE TITLE
webdriver-manager update doesn't seem to install chrome driver

### ISSUE THREAD

**Issue by bhreinb** [angular/webdriver-manager#66]
Hi there,

I have downloaded protractor via NPM. I navigate to the following directory and do the following commands

cd .\node_modules\protractor\bin
node webdriver-manager update --proxy <ProxyAddress>
node webdriver-manager start

This produces the following output....
seleniumProcess.pid: 26980
14:12:06.628 INFO - Launching a standalone Selenium Server
Setting system property webdriver.chrome.driver to C:\Users\bxb145\workspace\Sam
ple\node_modules\protractor\selenium\chromedriver_2.21.exe
14:12:06.785 INFO - Java: Oracle Corporation 25.91-b15
14:12:06.786 INFO - OS: Windows 7 6.1 amd64
14:12:06.794 INFO - v2.52.0, with Core v2.52.0. Built from revision 4c2593c
_**14:12:06.848 INFO - Driver class not found: com.opera.core.systems.OperaDriver
14:12:06.849 INFO - Driver provider com.opera.core.systems.OperaDriver is not re
gistered
14:12:06.858 INFO - Driver provider org.openqa.selenium.safari.SafariDriver regi
stration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform=
MAC}] does not match the current platform VISTA**_
14:12:07.079 INFO - RemoteWebDriver instances should connect to: http://127.0.0.
1:4444/wd/hub
14:12:07.079 INFO - Selenium Server is up and running

I try and execute some scripts via protractor

protractor conf_chromefirefox.js

config is the following....

exports.config = {
    framework: 'custom',
	
	// path relative to the current config file
	frameworkPath: require.resolve('protractor-cucumber-framework'),

	DirectConnect: true,
	
	allScriptsTimeout: 10000,

	// Capabilities to be passed to the webdriver instance.
	capabilities: {
    
		browserName: 'chrome',
		
		pageLoadingStrategy: 'eager',
		
		ignoreProtectedModeSettings: true
				
	},
	
	// Spec patterns are relative to the location of the spec file. They may include glob patterns.
	suites: {

		LoginExternal: 'Features/Cucumber/Helpers/Login.feature',
		
	},
    
	cucumberOpts:
	{
		
		require: ['Features/StepDefinitions/*_steps.js', 'features/support/World.js', 'features/support/Hooks.js', 'features/support/Common.js'],
		
        format: "pretty"
    
	},
	
	onPrepare: function() 
	{
		
		browser.manage().deleteAllCookies();
		
		//window.sessionStorage.clear();
		
		//window.localStorage.clear();
		
        browser.driver.manage().window().maximize();
        
        browser.ignoreSynchronization = false;
    
	}

};

when I run via protractor I get this error

path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at C:\Users\bxb145\workspace\Sample\node_modules\selenium-webdriver\safari.js:84:29
    at Object.<anonymous> (C:\Users\bxb145\workspace\Sample\node_modules\selenium-webdriver\safari.js:98:3)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

which is related (I think to the safari registration error message above). In that when it starts up it looks for safari driver. Why i do not know. How do I configure webdriver-manager so that it will not use safari? Any help appreciated with this as I'm unable to proceed past this and it is blocking me.

**Comment by cnishina** [comment]
The log message from selenium standalone server shows that it tried to match the capabilities but the platform you are using is VISTA. And that safari is not part of it.

When running `webdriver-manager start` my logs say:
```
Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities[{browserName=safari, version=, platform=MAC}] does not match the current platform WIN10
```

Looking into this: protractor-cucumber-framework uses protractor 3.2.0 which webdriver-manager was part of the protractor repo. It uses selenium-webdriver version 2.52.0.

selenium-webdriver 2.52.0 safari.js line 84:
```
 81  } else if (process.platform === 'win32') {
 82     var appDataDir = path.join(process.env['APPDATA'],
 83         'Apple Computer', 'Safari');
 84     var localDataDir = path.join(process.env['LOCALAPPDATA'],
 85         'Apple Computer', 'Safari');
```

Potentially what is happening is that process.env['LOCALAPPDATA'] is returning null. When I run this in node console:

```
>: node
>: process.env['LOCALAPPDATA']
C:\\Users\\{username}\\AppData\\Local
```

This is not reproducible. This appears to be a setup / environment issue with your computer. Closing this.

**Comment by bsrikan** [comment]
@cnishina I face similar issue trying to run protractor e2e test.
```
[09:47:00] I/file_manager - creating folder C:\jenkins\workspace\dhf-qs-develop-winserver2012\quick-start\node_modules\protractor\node_modules\webdriver-manager\selenium
[09:47:02] I/update - chromedriver: unzipping chromedriver_2.40.zip
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:499:7)
    at C:\jenkins\workspace\dhf-qs-develop-winserver2012\quick-start\node_modules\webdriver-js-extender\node_modules\selenium-webdriver\safari.js:62:17
    at Object.<anonymous> (C:\jenkins\workspace\dhf-qs-develop-winserver2012\quick-start\node_modules\webdriver-js-extender\node_modules\selenium-webdriver\safari.js:66:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
An unexpected error occured: undefined
```

I tried running `webdriver-manager start` to see what selenium standalone server says. Didnt see any error there:
```
$ node webdriver-manager start
[10:18:57] I/start - java -Dwebdriver.chrome.driver=C:\jenkins\workspace\dhf-qs-develop-winserver2012\quick-start\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.40.exe -Dwebdriver.gecko.driver=C:\jenkins\workspace\dhf-qs-develop-winserver2012\quick-start\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodriver-v0.21.0.exe -jar C:\jenkins\workspace\dhf-qs-develop-winserver2012\quick-start\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.13.0.jar -port 4444
[10:18:57] I/start - seleniumProcess.pid: 4400
10:18:58.271 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.13.0', revision: '2f0d292'
10:18:58.273 INFO [GridLauncherV3$1.launch] - Launching a standalone Selenium Server on port 4444
2018-07-23 10:18:58.512:INFO::main: Logging initialized @706ms to org.seleniumhq.jetty9.util.log.StdErrLog
10:18:58.966 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
```

framework: jasmine
selenium version: 3.13.0
windows: w2k12
Corresponding safari.js line 62:
```
 61   } else if (process.platform === 'win32') {
 62    return path.join(process.env['APPDATA'], 'Apple Computer', 'Safari');
 63   } else {
 64    return '/dev/null';
```

Appreciate any help/pointer.
Thanks!

**Comment by cnishina** [comment]
From your stacktrace, it appears that `webdriver-js-extender` is the problem. `webdriver-manager` does not use the `webdriver-js-extender` as a dependency. See https://github.com/angular/webdriver-manager/blob/master/package.json 

My guess is that Protractor or the `webdriver-js-extender` node module is having some issues. https://github.com/angular/webdriver-js-extender/issues

One of the issues that is listed in `webdriver-js-extender` is the selenium webdriver version. I would check out your path and see if you have multiple selenium-webdrivers installed. This can cause a lot of problems when versions are different.
