### ISSUE TITLE
webdriver-manager start --ie32 starts up x64 version

### ISSUE THREAD

**Issue by cnishina** [angular/webdriver-manager#68]

**Comment by lufecir** [comment]
I’m sorry, but it still does not work for me. The ‘ie32’ command line option passed to ‘webdriver start’ is ignored. 

I did some debugging and the code added in https://github.com/angular/webdriver-manager/commit/8b61b71410dbca6e205fbc599b954fe61a8ee937 is not executed:
 
As far as I could see, the ‘ie32’ option has not been defined for the ‘start’ command CLI, so the option is simply ignored when program.run is called.

Adding the following line in the top section of ‘start.js’ seemed to work for me:

`.addOption(opts_1.Opts[Opt.IE32])`

I did not check out the source code, so I did not verify what the equivalent code in TypeScript should be in 'start.ts'.

**Comment by cnishina** [comment]
Yup... It wasn't added to the options array.
