### ISSUE TITLE
webdriver-manager update standalone.jar failed when behind proxy

### ISSUE THREAD

**Issue by yongzoux0229** [angular/webdriver-manager#79]
my company need proxy to access network, so I run webdriver-manager update --proxy=<proxy_adress>, but  I got below errow:
[17:04:02] E/downloader - Connection timeout downloading: https://selenium-release.storage.googleapis.com/2.53/selenium-server-sta
ndalone-2.53.1.jar
[17:04:02] E/downloader - Default timeout is 4 minutes.
[17:04:02] E/downloader - { [Error: connect ETIMEDOUT 216.58.218.240:443]

After look into the source code: lib/cmds/update.ts, the issue  seems exist in below lines: 
```
  if (standalone) {
    let binary = binaries[StandAlone.id];
    FileManager.toDownload(binary, outputDir).then((value: boolean) => {
      if (value) {
        Downloader.downloadBinary(binary, outputDir);   **//it skiped to pass proxy and ignore_ssl at here**
```
update workd after I changed it to `Downloader.downloadBinary(binary_1, outputDir, proxy, ignoreSSL)`

FYI, you can notcie the source code to download the chrome.exe or IE.exe with proxy and ignoreSSL be passed

**Comment by cnishina** [comment]
Thanks for looking into this. I'll have a fix up soon.
