### ISSUE TITLE
Outdated chromedriver being downloaded

### ISSUE THREAD

**Issue by grushler** [angular/webdriver-manager#90]
When I perform `webdriver-manager update` I get chromedriver getting downloaded with version `2.21` whereas the latest one posted in chromedriver download site - https://sites.google.com/a/chromium.org/chromedriver/downloads is `2.23`.

Command `webdriver-manager status` gives -
```
selenium standalone versions available: 2.52.0 [default]
chromedriver versions available: 2.21 [default]
```

Could it be updated to use the latest version?
Thanks!

**Comment by cnishina** [comment]
This could be the latest version... I'll add that as the default. You could also download 2.23 with `webdriver-manager update --versions.chrome=2.23`
